// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: clients/auth_service.proto

package clientsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Pair_FullMethodName    = "/woodhouse.api.v1.clients.AuthService/Pair"
	AuthService_Refresh_FullMethodName = "/woodhouse.api.v1.clients.AuthService/Refresh"
	AuthService_Logout_FullMethodName  = "/woodhouse.api.v1.clients.AuthService/Logout"
	AuthService_Ping_FullMethodName    = "/woodhouse.api.v1.clients.AuthService/Ping"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Pair with (login to) the woodhouse core server. The bi-directional stream
	// is normally used in 'insecure' mode (i.e. use 'insecure skip verify' TLS
	// option); the channel is authenticated by a commitment-based Short
	// Authentication String (SAS) that the user compares on both the client CLI
	// and the server web UI. The pattern is:
	//  1. The client starts the stream by sending its client_id and an ephemeral
	//     X25519 client_pubkey (PKa).
	//  2. The server replies with KeyExchange, carrying its ephemeral X25519
	//     server_pubkey (PKb) and a commitment to its 32-byte nonce Nb:
	//     commitment = SHA256(len‖PKb ‖ len‖PKa ‖ len‖client_id ‖ len‖Nb).
	//  3. The client sends its own 32-byte nonce Na (client_nonce).
	//  4. The server replies with Reveal, carrying server_nonce = Nb.
	//  5. The client verifies the commitment, then both sides compute the shared
	//     ECDH secret and derive, via HKDF with distinct info labels:
	//     - an 8-digit SAS (displayed on both ends for the user to compare);
	//     - a 32-byte AES-256 session key.
	//  6. The server stores the SAS on the pairing request (shown in the web UI)
	//     and sends periodic Pending keepalives while awaiting the user.
	//  7. The user compares the two 8-digit codes and clicks Confirm (or Deny).
	//  8. On confirm the server sends Confirmed with data = Encrypt(cert), then a
	//     further message with data = Encrypt(refresh token), each AES-256-GCM
	//     encrypted under the session key. On deny/timeout it returns
	//     PermissionDenied and sends nothing.
	Pair(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PairRequest, PairResponse], error)
	// Refresh session auth tokens. Should be called regularly before tokens
	// expire.
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Logout the session.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// A simple ping of the server.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Pair(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PairRequest, PairResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthService_ServiceDesc.Streams[0], AuthService_Pair_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PairRequest, PairResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_PairClient = grpc.BidiStreamingClient[PairRequest, PairResponse]

func (c *authServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, AuthService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AuthService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// Pair with (login to) the woodhouse core server. The bi-directional stream
	// is normally used in 'insecure' mode (i.e. use 'insecure skip verify' TLS
	// option); the channel is authenticated by a commitment-based Short
	// Authentication String (SAS) that the user compares on both the client CLI
	// and the server web UI. The pattern is:
	//  1. The client starts the stream by sending its client_id and an ephemeral
	//     X25519 client_pubkey (PKa).
	//  2. The server replies with KeyExchange, carrying its ephemeral X25519
	//     server_pubkey (PKb) and a commitment to its 32-byte nonce Nb:
	//     commitment = SHA256(len‖PKb ‖ len‖PKa ‖ len‖client_id ‖ len‖Nb).
	//  3. The client sends its own 32-byte nonce Na (client_nonce).
	//  4. The server replies with Reveal, carrying server_nonce = Nb.
	//  5. The client verifies the commitment, then both sides compute the shared
	//     ECDH secret and derive, via HKDF with distinct info labels:
	//     - an 8-digit SAS (displayed on both ends for the user to compare);
	//     - a 32-byte AES-256 session key.
	//  6. The server stores the SAS on the pairing request (shown in the web UI)
	//     and sends periodic Pending keepalives while awaiting the user.
	//  7. The user compares the two 8-digit codes and clicks Confirm (or Deny).
	//  8. On confirm the server sends Confirmed with data = Encrypt(cert), then a
	//     further message with data = Encrypt(refresh token), each AES-256-GCM
	//     encrypted under the session key. On deny/timeout it returns
	//     PermissionDenied and sends nothing.
	Pair(grpc.BidiStreamingServer[PairRequest, PairResponse]) error
	// Refresh session auth tokens. Should be called regularly before tokens
	// expire.
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Logout the session.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// A simple ping of the server.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Pair(grpc.BidiStreamingServer[PairRequest, PairResponse]) error {
	return status.Error(codes.Unimplemented, "method Pair not implemented")
}
func (UnimplementedAuthServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Pair_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthServiceServer).Pair(&grpc.GenericServerStream[PairRequest, PairResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_PairServer = grpc.BidiStreamingServer[PairRequest, PairResponse]

func _AuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.v1.clients.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refresh",
			Handler:    _AuthService_Refresh_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AuthService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pair",
			Handler:       _AuthService_Pair_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "clients/auth_service.proto",
}
