// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: clients/auth_service.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairResponse_State int32

const (
	PairResponse_Undefined   PairResponse_State = 0
	PairResponse_Pending     PairResponse_State = 1 // Keepalive while awaiting the user's confirm/deny.
	PairResponse_KeyExchange PairResponse_State = 2 // Carries server_pubkey and commitment.
	PairResponse_Reveal      PairResponse_State = 3 // Carries server_nonce.
	PairResponse_Confirmed   PairResponse_State = 4 // Carries the first encrypted payload (the cert).
)

// Enum value maps for PairResponse_State.
var (
	PairResponse_State_name = map[int32]string{
		0: "Undefined",
		1: "Pending",
		2: "KeyExchange",
		3: "Reveal",
		4: "Confirmed",
	}
	PairResponse_State_value = map[string]int32{
		"Undefined":   0,
		"Pending":     1,
		"KeyExchange": 2,
		"Reveal":      3,
		"Confirmed":   4,
	}
)

func (x PairResponse_State) Enum() *PairResponse_State {
	p := new(PairResponse_State)
	*p = x
	return p
}

func (x PairResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PairResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_auth_service_proto_enumTypes[0].Descriptor()
}

func (PairResponse_State) Type() protoreflect.EnumType {
	return &file_clients_auth_service_proto_enumTypes[0]
}

func (x PairResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PairResponse_State.Descriptor instead.
func (PairResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{1, 0}
}

type PairRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientId          string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                            // Only needed in the first message.
	ClientName        string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`                      // Only needed in the first message.
	ClientDescription string                 `protobuf:"bytes,4,opt,name=client_description,json=clientDescription,proto3" json:"client_description,omitempty"` // Only needed in the first message.
	ClientVersion     string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`             // Only needed in the first message.
	ClientPubkey      []byte                 `protobuf:"bytes,6,opt,name=client_pubkey,json=clientPubkey,proto3" json:"client_pubkey,omitempty"`                // Ephemeral X25519 public key PKa (first message).
	ClientNonce       []byte                 `protobuf:"bytes,7,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`                   // 32-byte SAS nonce Na.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_clients_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *PairRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PairRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *PairRequest) GetClientDescription() string {
	if x != nil {
		return x.ClientDescription
	}
	return ""
}

func (x *PairRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *PairRequest) GetClientPubkey() []byte {
	if x != nil {
		return x.ClientPubkey
	}
	return nil
}

func (x *PairRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

type PairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PairResponse_State     `protobuf:"varint,1,opt,name=state,proto3,enum=woodhouse.api.v1.clients.PairResponse_State" json:"state,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                     // Encrypted cert / refresh-token payloads.
	ServerPubkey  []byte                 `protobuf:"bytes,3,opt,name=server_pubkey,json=serverPubkey,proto3" json:"server_pubkey,omitempty"` // Ephemeral X25519 public key PKb (KeyExchange).
	Commitment    []byte                 `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`                         // SHA-256 commitment to server_nonce (KeyExchange).
	ServerNonce   []byte                 `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`    // 32-byte SAS nonce Nb, revealed (Reveal).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_clients_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *PairResponse) GetState() PairResponse_State {
	if x != nil {
		return x.State
	}
	return PairResponse_Undefined
}

func (x *PairResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PairResponse) GetServerPubkey() []byte {
	if x != nil {
		return x.ServerPubkey
	}
	return nil
}

func (x *PairResponse) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *PairResponse) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_clients_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_clients_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_clients_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_clients_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{5}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_clients_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_clients_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_clients_auth_service_proto_rawDescGZIP(), []int{7}
}

var File_clients_auth_service_proto protoreflect.FileDescriptor

const file_clients_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1aclients/auth_service.proto\x12\x18woodhouse.api.v1.clients\"\xf5\x01\n" +
	"\vPairRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12-\n" +
	"\x12client_description\x18\x04 \x01(\tR\x11clientDescription\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\x12#\n" +
	"\rclient_pubkey\x18\x06 \x01(\fR\fclientPubkey\x12!\n" +
	"\fclient_nonce\x18\a \x01(\fR\vclientNonceJ\x04\b\x02\x10\x03R\x04data\"\x9f\x02\n" +
	"\fPairResponse\x12B\n" +
	"\x05state\x18\x01 \x01(\x0e2,.woodhouse.api.v1.clients.PairResponse.StateR\x05state\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12#\n" +
	"\rserver_pubkey\x18\x03 \x01(\fR\fserverPubkey\x12\x1e\n" +
	"\n" +
	"commitment\x18\x04 \x01(\fR\n" +
	"commitment\x12!\n" +
	"\fserver_nonce\x18\x05 \x01(\fR\vserverNonce\"O\n" +
	"\x05State\x12\r\n" +
	"\tUndefined\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\x0f\n" +
	"\vKeyExchange\x10\x02\x12\n" +
	"\n" +
	"\x06Reveal\x10\x03\x12\r\n" +
	"\tConfirmed\x10\x04\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Y\n" +
	"\x0fRefreshResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse2\xfc\x02\n" +
	"\vAuthService\x12Y\n" +
	"\x04Pair\x12%.woodhouse.api.v1.clients.PairRequest\x1a&.woodhouse.api.v1.clients.PairResponse(\x010\x01\x12^\n" +
	"\aRefresh\x12(.woodhouse.api.v1.clients.RefreshRequest\x1a).woodhouse.api.v1.clients.RefreshResponse\x12[\n" +
	"\x06Logout\x12'.woodhouse.api.v1.clients.LogoutRequest\x1a(.woodhouse.api.v1.clients.LogoutResponse\x12U\n" +
	"\x04Ping\x12%.woodhouse.api.v1.clients.PingRequest\x1a&.woodhouse.api.v1.clients.PingResponseB=Z;github.com/jimjibone/woodhouse-api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_auth_service_proto_rawDescOnce sync.Once
	file_clients_auth_service_proto_rawDescData []byte
)

func file_clients_auth_service_proto_rawDescGZIP() []byte {
	file_clients_auth_service_proto_rawDescOnce.Do(func() {
		file_clients_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_auth_service_proto_rawDesc), len(file_clients_auth_service_proto_rawDesc)))
	})
	return file_clients_auth_service_proto_rawDescData
}

var file_clients_auth_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clients_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_clients_auth_service_proto_goTypes = []any{
	(PairResponse_State)(0), // 0: woodhouse.api.v1.clients.PairResponse.State
	(*PairRequest)(nil),     // 1: woodhouse.api.v1.clients.PairRequest
	(*PairResponse)(nil),    // 2: woodhouse.api.v1.clients.PairResponse
	(*RefreshRequest)(nil),  // 3: woodhouse.api.v1.clients.RefreshRequest
	(*RefreshResponse)(nil), // 4: woodhouse.api.v1.clients.RefreshResponse
	(*LogoutRequest)(nil),   // 5: woodhouse.api.v1.clients.LogoutRequest
	(*LogoutResponse)(nil),  // 6: woodhouse.api.v1.clients.LogoutResponse
	(*PingRequest)(nil),     // 7: woodhouse.api.v1.clients.PingRequest
	(*PingResponse)(nil),    // 8: woodhouse.api.v1.clients.PingResponse
}
var file_clients_auth_service_proto_depIdxs = []int32{
	0, // 0: woodhouse.api.v1.clients.PairResponse.state:type_name -> woodhouse.api.v1.clients.PairResponse.State
	1, // 1: woodhouse.api.v1.clients.AuthService.Pair:input_type -> woodhouse.api.v1.clients.PairRequest
	3, // 2: woodhouse.api.v1.clients.AuthService.Refresh:input_type -> woodhouse.api.v1.clients.RefreshRequest
	5, // 3: woodhouse.api.v1.clients.AuthService.Logout:input_type -> woodhouse.api.v1.clients.LogoutRequest
	7, // 4: woodhouse.api.v1.clients.AuthService.Ping:input_type -> woodhouse.api.v1.clients.PingRequest
	2, // 5: woodhouse.api.v1.clients.AuthService.Pair:output_type -> woodhouse.api.v1.clients.PairResponse
	4, // 6: woodhouse.api.v1.clients.AuthService.Refresh:output_type -> woodhouse.api.v1.clients.RefreshResponse
	6, // 7: woodhouse.api.v1.clients.AuthService.Logout:output_type -> woodhouse.api.v1.clients.LogoutResponse
	8, // 8: woodhouse.api.v1.clients.AuthService.Ping:output_type -> woodhouse.api.v1.clients.PingResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clients_auth_service_proto_init() }
func file_clients_auth_service_proto_init() {
	if File_clients_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_auth_service_proto_rawDesc), len(file_clients_auth_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_auth_service_proto_goTypes,
		DependencyIndexes: file_clients_auth_service_proto_depIdxs,
		EnumInfos:         file_clients_auth_service_proto_enumTypes,
		MessageInfos:      file_clients_auth_service_proto_msgTypes,
	}.Build()
	File_clients_auth_service_proto = out.File
	file_clients_auth_service_proto_goTypes = nil
	file_clients_auth_service_proto_depIdxs = nil
}
