// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: clients/client_service.proto

package clientsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientService_StatusStream_FullMethodName     = "/woodhouse.api.v1.clients.ClientService/StatusStream"
	ClientService_ActionStream_FullMethodName     = "/woodhouse.api.v1.clients.ClientService/ActionStream"
	ClientService_ImageStream_FullMethodName      = "/woodhouse.api.v1.clients.ClientService/ImageStream"
	ClientService_DeviceStream_FullMethodName     = "/woodhouse.api.v1.clients.ClientService/DeviceStream"
	ClientService_SendAction_FullMethodName       = "/woodhouse.api.v1.clients.ClientService/SendAction"
	ClientService_SendImageRequest_FullMethodName = "/woodhouse.api.v1.clients.ClientService/SendImageRequest"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	// StatusStream allows the client to stream StatusUpdates to the server. The
	// first StatusUpdate should contain the full state of the client and any
	// subsequent update should only contain diffs - i.e. include the
	// client_info and all devices. See the Device type for what to include in a
	// full state update.
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatusUpdate, Empty], error)
	// ActionStream allows the client to receive ActionRequests from the server
	// (when they are created by users or automations). The client must
	// eventually respond to all ActionRequests by sending an ActionResponse
	// with the same ID and the current status of the action (this allows for
	// reactive user interfaces and automations to implement retries, etc).
	ActionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionResponse, ActionRequest], error)
	ImageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ImageResponse, ImageRequest], error)
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DeviceStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceStreamRequest, DeviceStreamResponse], error)
	// Send an action to a device service.
	SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error)
	// Send an image request to a device service.
	SendImageRequest(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageResponse], error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatusUpdate, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[0], ClientService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusUpdate, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_StatusStreamClient = grpc.ClientStreamingClient[StatusUpdate, Empty]

func (c *clientServiceClient) ActionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionResponse, ActionRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[1], ClientService_ActionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionResponse, ActionRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_ActionStreamClient = grpc.BidiStreamingClient[ActionResponse, ActionRequest]

func (c *clientServiceClient) ImageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ImageResponse, ImageRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[2], ClientService_ImageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageResponse, ImageRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_ImageStreamClient = grpc.BidiStreamingClient[ImageResponse, ImageRequest]

func (c *clientServiceClient) DeviceStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceStreamRequest, DeviceStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[3], ClientService_DeviceStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceStreamRequest, DeviceStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_DeviceStreamClient = grpc.BidiStreamingClient[DeviceStreamRequest, DeviceStreamResponse]

func (c *clientServiceClient) SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[4], ClientService_SendAction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionRequest, ActionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SendActionClient = grpc.ServerStreamingClient[ActionResponse]

func (c *clientServiceClient) SendImageRequest(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[5], ClientService_SendImageRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageRequest, ImageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SendImageRequestClient = grpc.ServerStreamingClient[ImageResponse]

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	// StatusStream allows the client to stream StatusUpdates to the server. The
	// first StatusUpdate should contain the full state of the client and any
	// subsequent update should only contain diffs - i.e. include the
	// client_info and all devices. See the Device type for what to include in a
	// full state update.
	StatusStream(grpc.ClientStreamingServer[StatusUpdate, Empty]) error
	// ActionStream allows the client to receive ActionRequests from the server
	// (when they are created by users or automations). The client must
	// eventually respond to all ActionRequests by sending an ActionResponse
	// with the same ID and the current status of the action (this allows for
	// reactive user interfaces and automations to implement retries, etc).
	ActionStream(grpc.BidiStreamingServer[ActionResponse, ActionRequest]) error
	ImageStream(grpc.BidiStreamingServer[ImageResponse, ImageRequest]) error
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DeviceStream(grpc.BidiStreamingServer[DeviceStreamRequest, DeviceStreamResponse]) error
	// Send an action to a device service.
	SendAction(*ActionRequest, grpc.ServerStreamingServer[ActionResponse]) error
	// Send an image request to a device service.
	SendImageRequest(*ImageRequest, grpc.ServerStreamingServer[ImageResponse]) error
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) StatusStream(grpc.ClientStreamingServer[StatusUpdate, Empty]) error {
	return status.Error(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedClientServiceServer) ActionStream(grpc.BidiStreamingServer[ActionResponse, ActionRequest]) error {
	return status.Error(codes.Unimplemented, "method ActionStream not implemented")
}
func (UnimplementedClientServiceServer) ImageStream(grpc.BidiStreamingServer[ImageResponse, ImageRequest]) error {
	return status.Error(codes.Unimplemented, "method ImageStream not implemented")
}
func (UnimplementedClientServiceServer) DeviceStream(grpc.BidiStreamingServer[DeviceStreamRequest, DeviceStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method DeviceStream not implemented")
}
func (UnimplementedClientServiceServer) SendAction(*ActionRequest, grpc.ServerStreamingServer[ActionResponse]) error {
	return status.Error(codes.Unimplemented, "method SendAction not implemented")
}
func (UnimplementedClientServiceServer) SendImageRequest(*ImageRequest, grpc.ServerStreamingServer[ImageResponse]) error {
	return status.Error(codes.Unimplemented, "method SendImageRequest not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call panics, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).StatusStream(&grpc.GenericServerStream[StatusUpdate, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_StatusStreamServer = grpc.ClientStreamingServer[StatusUpdate, Empty]

func _ClientService_ActionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).ActionStream(&grpc.GenericServerStream[ActionResponse, ActionRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_ActionStreamServer = grpc.BidiStreamingServer[ActionResponse, ActionRequest]

func _ClientService_ImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).ImageStream(&grpc.GenericServerStream[ImageResponse, ImageRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_ImageStreamServer = grpc.BidiStreamingServer[ImageResponse, ImageRequest]

func _ClientService_DeviceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).DeviceStream(&grpc.GenericServerStream[DeviceStreamRequest, DeviceStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_DeviceStreamServer = grpc.BidiStreamingServer[DeviceStreamRequest, DeviceStreamResponse]

func _ClientService_SendAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).SendAction(m, &grpc.GenericServerStream[ActionRequest, ActionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SendActionServer = grpc.ServerStreamingServer[ActionResponse]

func _ClientService_SendImageRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).SendImageRequest(m, &grpc.GenericServerStream[ImageRequest, ImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_SendImageRequestServer = grpc.ServerStreamingServer[ImageResponse]

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.v1.clients.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _ClientService_StatusStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ActionStream",
			Handler:       _ClientService_ActionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ImageStream",
			Handler:       _ClientService_ImageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeviceStream",
			Handler:       _ClientService_DeviceStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendAction",
			Handler:       _ClientService_SendAction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendImageRequest",
			Handler:       _ClientService_SendImageRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clients/client_service.proto",
}
