// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: clients/client.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Paired        bool                   `protobuf:"varint,5,opt,name=paired,proto3" json:"paired,omitempty"`
	Online        bool                   `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	FirstSeen     uint64                 `protobuf:"varint,7,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"` // Seconds since Unix epoch 1970-01-01T00:00:00Z.
	LastSeen      uint64                 `protobuf:"varint,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // Seconds since Unix epoch 1970-01-01T00:00:00Z.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_clients_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_clients_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Client) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Client) GetPaired() bool {
	if x != nil {
		return x.Paired
	}
	return false
}

func (x *Client) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Client) GetFirstSeen() uint64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *Client) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RequestedAt   uint64                 `protobuf:"varint,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"` // Seconds since Unix epoch 1970-01-01T00:00:00Z.
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`        // Server-generated unique id for this pairing attempt.
	Sas           string                 `protobuf:"bytes,6,opt,name=sas,proto3" json:"sas,omitempty"`                                     // 8-digit SAS to compare against the client CLI (empty until known).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	mi := &file_clients_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_clients_client_proto_rawDescGZIP(), []int{1}
}

func (x *PairingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PairingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PairingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PairingRequest) GetRequestedAt() uint64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *PairingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PairingRequest) GetSas() string {
	if x != nil {
		return x.Sas
	}
	return ""
}

var File_clients_client_proto protoreflect.FileDescriptor

const file_clients_client_proto_rawDesc = "" +
	"\n" +
	"\x14clients/client.proto\x12\x18woodhouse.api.v1.clients\"\xd4\x01\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06paired\x18\x05 \x01(\bR\x06paired\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\x12\x1d\n" +
	"\n" +
	"first_seen\x18\a \x01(\x04R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\b \x01(\x04R\blastSeen\"\xb7\x01\n" +
	"\x0ePairingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\frequested_at\x18\x04 \x01(\x04R\vrequestedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x10\n" +
	"\x03sas\x18\x06 \x01(\tR\x03sasB=Z;github.com/jimjibone/woodhouse-api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_client_proto_rawDescOnce sync.Once
	file_clients_client_proto_rawDescData []byte
)

func file_clients_client_proto_rawDescGZIP() []byte {
	file_clients_client_proto_rawDescOnce.Do(func() {
		file_clients_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_client_proto_rawDesc), len(file_clients_client_proto_rawDesc)))
	})
	return file_clients_client_proto_rawDescData
}

var file_clients_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clients_client_proto_goTypes = []any{
	(*Client)(nil),         // 0: woodhouse.api.v1.clients.Client
	(*PairingRequest)(nil), // 1: woodhouse.api.v1.clients.PairingRequest
}
var file_clients_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clients_client_proto_init() }
func file_clients_client_proto_init() {
	if File_clients_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_client_proto_rawDesc), len(file_clients_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clients_client_proto_goTypes,
		DependencyIndexes: file_clients_client_proto_depIdxs,
		MessageInfos:      file_clients_client_proto_msgTypes,
	}.Build()
	File_clients_client_proto = out.File
	file_clients_client_proto_goTypes = nil
	file_clients_client_proto_depIdxs = nil
}
