// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: clients/client_service.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permissions int32

const (
	Permissions_PERM_UNDEFINED Permissions = 0
	Permissions_PERM_READONLY  Permissions = 1
	Permissions_PERM_WRITEONLY Permissions = 2
	Permissions_PERM_READWRITE Permissions = 3
)

// Enum value maps for Permissions.
var (
	Permissions_name = map[int32]string{
		0: "PERM_UNDEFINED",
		1: "PERM_READONLY",
		2: "PERM_WRITEONLY",
		3: "PERM_READWRITE",
	}
	Permissions_value = map[string]int32{
		"PERM_UNDEFINED": 0,
		"PERM_READONLY":  1,
		"PERM_WRITEONLY": 2,
		"PERM_READWRITE": 3,
	}
)

func (x Permissions) Enum() *Permissions {
	p := new(Permissions)
	*p = x
	return p
}

func (x Permissions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permissions) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[0].Descriptor()
}

func (Permissions) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[0]
}

func (x Permissions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permissions.Descriptor instead.
func (Permissions) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{0}
}

type Unit int32

const (
	Unit_UNIT_UNDEFINED                  Unit = 0
	Unit_UNIT_PERCENTAGE                 Unit = 1  // %
	Unit_UNIT_ARC_DEGREES                Unit = 2  // °
	Unit_UNIT_CELSIUS                    Unit = 3  // °C
	Unit_UNIT_LUX                        Unit = 4  // lux
	Unit_UNIT_SECONDS                    Unit = 5  // seconds
	Unit_UNIT_PPM                        Unit = 6  // ppm
	Unit_UNIT_MICROGRAMS_PER_CUBIC_METER Unit = 7  // micrograms/m^3
	Unit_UNIT_VOLTS                      Unit = 8  // volts
	Unit_UNIT_AMPS                       Unit = 9  // amps
	Unit_UNIT_WATTS                      Unit = 10 // watts
	Unit_UNIT_MIREDS                     Unit = 11 // mireds
	Unit_UNIT_HECTOPASCAL                Unit = 12 // hPa
	Unit_UNIT_METERS                     Unit = 13 // meters
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0:  "UNIT_UNDEFINED",
		1:  "UNIT_PERCENTAGE",
		2:  "UNIT_ARC_DEGREES",
		3:  "UNIT_CELSIUS",
		4:  "UNIT_LUX",
		5:  "UNIT_SECONDS",
		6:  "UNIT_PPM",
		7:  "UNIT_MICROGRAMS_PER_CUBIC_METER",
		8:  "UNIT_VOLTS",
		9:  "UNIT_AMPS",
		10: "UNIT_WATTS",
		11: "UNIT_MIREDS",
		12: "UNIT_HECTOPASCAL",
		13: "UNIT_METERS",
	}
	Unit_value = map[string]int32{
		"UNIT_UNDEFINED":                  0,
		"UNIT_PERCENTAGE":                 1,
		"UNIT_ARC_DEGREES":                2,
		"UNIT_CELSIUS":                    3,
		"UNIT_LUX":                        4,
		"UNIT_SECONDS":                    5,
		"UNIT_PPM":                        6,
		"UNIT_MICROGRAMS_PER_CUBIC_METER": 7,
		"UNIT_VOLTS":                      8,
		"UNIT_AMPS":                       9,
		"UNIT_WATTS":                      10,
		"UNIT_MIREDS":                     11,
		"UNIT_HECTOPASCAL":                12,
		"UNIT_METERS":                     13,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[1].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[1]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{1}
}

type ActionResponse_ActionStatus int32

const (
	ActionResponse_UNDEFINED ActionResponse_ActionStatus = 0 // No status defined.
	ActionResponse_QUEUED    ActionResponse_ActionStatus = 1 // The action is queued for transmission to the device.
	ActionResponse_SENT      ActionResponse_ActionStatus = 2 // The action has been sent to the device.
	// Note all enums beyond this point indicate a final response.
	ActionResponse_COMPLETE     ActionResponse_ActionStatus = 3 // The action was completed by the device.
	ActionResponse_TIMEOUT      ActionResponse_ActionStatus = 4 // The action was not acknowledged by the device before the timeout.
	ActionResponse_CANCELED     ActionResponse_ActionStatus = 5 // The action was canceled before a final response was received.
	ActionResponse_ERROR        ActionResponse_ActionStatus = 6 // The action failed due to an error. See details.
	ActionResponse_ERR_READONLY ActionResponse_ActionStatus = 7 // The action contained a write to a read only attribute.
)

// Enum value maps for ActionResponse_ActionStatus.
var (
	ActionResponse_ActionStatus_name = map[int32]string{
		0: "UNDEFINED",
		1: "QUEUED",
		2: "SENT",
		3: "COMPLETE",
		4: "TIMEOUT",
		5: "CANCELED",
		6: "ERROR",
		7: "ERR_READONLY",
	}
	ActionResponse_ActionStatus_value = map[string]int32{
		"UNDEFINED":    0,
		"QUEUED":       1,
		"SENT":         2,
		"COMPLETE":     3,
		"TIMEOUT":      4,
		"CANCELED":     5,
		"ERROR":        6,
		"ERR_READONLY": 7,
	}
)

func (x ActionResponse_ActionStatus) Enum() *ActionResponse_ActionStatus {
	p := new(ActionResponse_ActionStatus)
	*p = x
	return p
}

func (x ActionResponse_ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionResponse_ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[2].Descriptor()
}

func (ActionResponse_ActionStatus) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[2]
}

func (x ActionResponse_ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionResponse_ActionStatus.Descriptor instead.
func (ActionResponse_ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{3, 0}
}

type ImageResponse_ImageStatus int32

const (
	ImageResponse_UNDEFINED ImageResponse_ImageStatus = 0 // No status defined.
	ImageResponse_PENDING   ImageResponse_ImageStatus = 1 // The action is queued for transmission to the device.
	ImageResponse_SENT      ImageResponse_ImageStatus = 2 // The action has been sent to the device.
	// Note all enums beyond this point indicate a final response.
	ImageResponse_COMPLETE ImageResponse_ImageStatus = 3 // The action was completed by the device.
	ImageResponse_TIMEOUT  ImageResponse_ImageStatus = 4 // The action was not acknowledged by the device before the timeout.
	ImageResponse_CANCELED ImageResponse_ImageStatus = 5 // The action was canceled before a final response was received.
	ImageResponse_ERROR    ImageResponse_ImageStatus = 6 // The action failed due to an error. See details.
)

// Enum value maps for ImageResponse_ImageStatus.
var (
	ImageResponse_ImageStatus_name = map[int32]string{
		0: "UNDEFINED",
		1: "PENDING",
		2: "SENT",
		3: "COMPLETE",
		4: "TIMEOUT",
		5: "CANCELED",
		6: "ERROR",
	}
	ImageResponse_ImageStatus_value = map[string]int32{
		"UNDEFINED": 0,
		"PENDING":   1,
		"SENT":      2,
		"COMPLETE":  3,
		"TIMEOUT":   4,
		"CANCELED":  5,
		"ERROR":     6,
	}
)

func (x ImageResponse_ImageStatus) Enum() *ImageResponse_ImageStatus {
	p := new(ImageResponse_ImageStatus)
	*p = x
	return p
}

func (x ImageResponse_ImageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageResponse_ImageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[3].Descriptor()
}

func (ImageResponse_ImageStatus) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[3]
}

func (x ImageResponse_ImageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageResponse_ImageStatus.Descriptor instead.
func (ImageResponse_ImageStatus) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{8, 0}
}

type Device_DeviceType int32

const (
	Device_UNDEFINED Device_DeviceType = 0
	Device_BRIDGE    Device_DeviceType = 1
	Device_REACTOR   Device_DeviceType = 2
	Device_DEVICE    Device_DeviceType = 3
	Device_GROUPED   Device_DeviceType = 4
)

// Enum value maps for Device_DeviceType.
var (
	Device_DeviceType_name = map[int32]string{
		0: "UNDEFINED",
		1: "BRIDGE",
		2: "REACTOR",
		3: "DEVICE",
		4: "GROUPED",
	}
	Device_DeviceType_value = map[string]int32{
		"UNDEFINED": 0,
		"BRIDGE":    1,
		"REACTOR":   2,
		"DEVICE":    3,
		"GROUPED":   4,
	}
)

func (x Device_DeviceType) Enum() *Device_DeviceType {
	p := new(Device_DeviceType)
	*p = x
	return p
}

func (x Device_DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Device_DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[4].Descriptor()
}

func (Device_DeviceType) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[4]
}

func (x Device_DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Device_DeviceType.Descriptor instead.
func (Device_DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{9, 0}
}

type Service_ServiceType int32

const (
	Service_UNDEFINED   Service_ServiceType = 0
	Service_INFO        Service_ServiceType = 1
	Service_ONLINE      Service_ServiceType = 2
	Service_GENERIC     Service_ServiceType = 3
	Service_INPUT       Service_ServiceType = 4
	Service_RELAY       Service_ServiceType = 5
	Service_LIGHTBULB   Service_ServiceType = 6
	Service_CLIMATE     Service_ServiceType = 7
	Service_BATTERY     Service_ServiceType = 8
	Service_BUTTON      Service_ServiceType = 9
	Service_ENVIRONMENT Service_ServiceType = 10
	Service_CONTACT     Service_ServiceType = 11
	Service_UPDATE      Service_ServiceType = 12
	Service_BOOL        Service_ServiceType = 13
	Service_INT         Service_ServiceType = 14
	Service_FLOAT       Service_ServiceType = 15
	Service_TEXT        Service_ServiceType = 16
	Service_DURATION    Service_ServiceType = 17
	Service_TIME        Service_ServiceType = 18
	Service_COLOR       Service_ServiceType = 19
	Service_ENUM        Service_ServiceType = 20
	Service_CAMERA      Service_ServiceType = 21
	Service_COVER       Service_ServiceType = 22
	Service_MOTION      Service_ServiceType = 23
	Service_PRESENCE    Service_ServiceType = 24
)

// Enum value maps for Service_ServiceType.
var (
	Service_ServiceType_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "INFO",
		2:  "ONLINE",
		3:  "GENERIC",
		4:  "INPUT",
		5:  "RELAY",
		6:  "LIGHTBULB",
		7:  "CLIMATE",
		8:  "BATTERY",
		9:  "BUTTON",
		10: "ENVIRONMENT",
		11: "CONTACT",
		12: "UPDATE",
		13: "BOOL",
		14: "INT",
		15: "FLOAT",
		16: "TEXT",
		17: "DURATION",
		18: "TIME",
		19: "COLOR",
		20: "ENUM",
		21: "CAMERA",
		22: "COVER",
		23: "MOTION",
		24: "PRESENCE",
	}
	Service_ServiceType_value = map[string]int32{
		"UNDEFINED":   0,
		"INFO":        1,
		"ONLINE":      2,
		"GENERIC":     3,
		"INPUT":       4,
		"RELAY":       5,
		"LIGHTBULB":   6,
		"CLIMATE":     7,
		"BATTERY":     8,
		"BUTTON":      9,
		"ENVIRONMENT": 10,
		"CONTACT":     11,
		"UPDATE":      12,
		"BOOL":        13,
		"INT":         14,
		"FLOAT":       15,
		"TEXT":        16,
		"DURATION":    17,
		"TIME":        18,
		"COLOR":       19,
		"ENUM":        20,
		"CAMERA":      21,
		"COVER":       22,
		"MOTION":      23,
		"PRESENCE":    24,
	}
)

func (x Service_ServiceType) Enum() *Service_ServiceType {
	p := new(Service_ServiceType)
	*p = x
	return p
}

func (x Service_ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_client_service_proto_enumTypes[5].Descriptor()
}

func (Service_ServiceType) Type() protoreflect.EnumType {
	return &file_clients_client_service_proto_enumTypes[5]
}

func (x Service_ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_ServiceType.Descriptor instead.
func (Service_ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{10, 0}
}

// Empty message is intentionally empty - i.e. it will never contain any data.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_clients_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{0}
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo    *ClientInfo            `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	DeviceInfo    []*Device              `protobuf:"bytes,2,rep,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_clients_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatusUpdate) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *StatusUpdate) GetDeviceInfo() []*Device {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`    // Set by the server.
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`    // ID of the device to send the action to.
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // ID of the service to control.
	Values        []*Value               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`                        // List of values to control (see attributes).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_clients_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *ActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ActionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ActionRequest) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ActionId      string                      `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Status        ActionResponse_ActionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=woodhouse.api.v1.clients.ActionResponse_ActionStatus" json:"status,omitempty"`
	Details       string                      `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_clients_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionResponse) GetStatus() ActionResponse_ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionResponse_UNDEFINED
}

func (x *ActionResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // The client ID (e.g. "zigbee").
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Name of the client (e.g. "Zigbee").
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of the client (e.g. "Provides support for Zigbee devices via zigbee2mqtt").
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`         // Version of the client (e.g. "0.1.0").
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_clients_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClientInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DeviceStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional request for a full device state to be sent on the stream. Useful
	// where a device state was previously ignored but is now required, without
	// having to restart the stream. The requested device state may not be sent
	// immediately but will be sent when the server is ready.
	GetDeviceId   string `protobuf:"bytes,1,opt,name=get_device_id,json=getDeviceId,proto3" json:"get_device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStreamRequest) Reset() {
	*x = DeviceStreamRequest{}
	mi := &file_clients_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStreamRequest) ProtoMessage() {}

func (x *DeviceStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStreamRequest.ProtoReflect.Descriptor instead.
func (*DeviceStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceStreamRequest) GetGetDeviceId() string {
	if x != nil {
		return x.GetDeviceId
	}
	return ""
}

type DeviceStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                                    // Optional: A device update, possibly containing the full state.
	DeviceRemoved string                 `protobuf:"bytes,2,opt,name=device_removed,json=deviceRemoved,proto3" json:"device_removed,omitempty"` // Optional: Indicates the device_id of a device that was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStreamResponse) Reset() {
	*x = DeviceStreamResponse{}
	mi := &file_clients_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStreamResponse) ProtoMessage() {}

func (x *DeviceStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStreamResponse.ProtoReflect.Descriptor instead.
func (*DeviceStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceStreamResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceStreamResponse) GetDeviceRemoved() string {
	if x != nil {
		return x.DeviceRemoved
	}
	return ""
}

type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // Set by the server.
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`          // ID of the device to send the action to.
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`       // ID of the service to request an image from.
	AttributeId   string                 `protobuf:"bytes,4,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"` // ID of the image attribute to request an image from.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_clients_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *ImageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ImageRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ImageRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ImageRequest) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

type ImageResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RequestId     string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        ImageResponse_ImageStatus `protobuf:"varint,2,opt,name=status,proto3,enum=woodhouse.api.v1.clients.ImageResponse_ImageStatus" json:"status,omitempty"`
	Details       string                    `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Data          []byte                    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_clients_client_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{8}
}

func (x *ImageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ImageResponse) GetStatus() ImageResponse_ImageStatus {
	if x != nil {
		return x.Status
	}
	return ImageResponse_UNDEFINED
}

func (x *ImageResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Device contains either the full or partial (update) state of a device. The id
// field must always be set. All devices are required to implement the Info and
// Online services, so if full_state is set to true these services must be
// included.
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // The universally unique device ID (typically a hardware address or other static and unique identifier and prefixed with the protocol, e.g. "zigbee00158d00045c089f").
	FullState     bool                   `protobuf:"varint,2,opt,name=full_state,json=fullState,proto3" json:"full_state,omitempty"`                    // Indicates that this message contains the entire state of the device.
	Typ           Device_DeviceType      `protobuf:"varint,3,opt,name=typ,proto3,enum=woodhouse.api.v1.clients.Device_DeviceType" json:"typ,omitempty"` // The general type of this device (helps with classification in user interfaces).
	Services      []*Service             `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`                                        // The services supported by the device and their states.
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                        // The ID of the client that provides this device. This is set by the core.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_clients_client_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{9}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetFullState() bool {
	if x != nil {
		return x.FullState
	}
	return false
}

func (x *Device) GetTyp() Device_DeviceType {
	if x != nil {
		return x.Typ
	}
	return Device_UNDEFINED
}

func (x *Device) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Device) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                      // The service ID (typically the name of the service type, e.g. "info").
	Typ           Service_ServiceType    `protobuf:"varint,2,opt,name=typ,proto3,enum=woodhouse.api.v1.clients.Service_ServiceType" json:"typ,omitempty"` // The type of the service.
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`                                                // Optional alias, sometimes used to differentiate between multiple services of the same type on a single device.
	Attrs         []*Attribute           `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty"`                                                // The attributes that make up this service.
	Favorite      bool                   `protobuf:"varint,5,opt,name=favorite,proto3" json:"favorite,omitempty"`                                         // Indicates if this service is a favorite.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_clients_client_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetTyp() Service_ServiceType {
	if x != nil {
		return x.Typ
	}
	return Service_UNDEFINED
}

func (x *Service) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Service) GetAttrs() []*Attribute {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Service) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID or name of the attribute.
	Bool  *BoolAttribute         `protobuf:"bytes,2,opt,name=bool,proto3" json:"bool,omitempty"`
	Int   *IntAttribute          `protobuf:"bytes,3,opt,name=int,proto3" json:"int,omitempty"`
	Float *FloatAttribute        `protobuf:"bytes,4,opt,name=float,proto3" json:"float,omitempty"`
	Text  *TextAttribute         `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// ActionAttribute    action     = 6;
	Duration *DurationAttribute `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Time     *TimeAttribute     `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	// ColorModeAttribute color_mode = 9;
	Color         *ColorAttribute `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	Enum          *EnumAttribute  `protobuf:"bytes,11,opt,name=enum,proto3" json:"enum,omitempty"`
	Image         *ImageAttribute `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"` // NumberScheduleAttribute number_schedule = 13;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_clients_client_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{11}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetBool() *BoolAttribute {
	if x != nil {
		return x.Bool
	}
	return nil
}

func (x *Attribute) GetInt() *IntAttribute {
	if x != nil {
		return x.Int
	}
	return nil
}

func (x *Attribute) GetFloat() *FloatAttribute {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *Attribute) GetText() *TextAttribute {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Attribute) GetDuration() *DurationAttribute {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Attribute) GetTime() *TimeAttribute {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Attribute) GetColor() *ColorAttribute {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Attribute) GetEnum() *EnumAttribute {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Attribute) GetImage() *ImageAttribute {
	if x != nil {
		return x.Image
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID or name of the attribute.
	Bool  *BoolValue             `protobuf:"bytes,2,opt,name=bool,proto3" json:"bool,omitempty"`
	Int   *IntValue              `protobuf:"bytes,3,opt,name=int,proto3" json:"int,omitempty"`
	Float *FloatValue            `protobuf:"bytes,4,opt,name=float,proto3" json:"float,omitempty"`
	Text  *TextValue             `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// ActionValue    action     = 6;
	Duration *DurationValue `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Time     *TimeValue     `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	// ColorModeValue color_mode = 9;
	Color         *ColorValue `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	Enum          *EnumValue  `protobuf:"bytes,11,opt,name=enum,proto3" json:"enum,omitempty"`
	Image         *ImageValue `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"` // NumberScheduleValue number_schedule = 13;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_clients_client_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Value) GetBool() *BoolValue {
	if x != nil {
		return x.Bool
	}
	return nil
}

func (x *Value) GetInt() *IntValue {
	if x != nil {
		return x.Int
	}
	return nil
}

func (x *Value) GetFloat() *FloatValue {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *Value) GetText() *TextValue {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Value) GetDuration() *DurationValue {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Value) GetTime() *TimeValue {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Value) GetColor() *ColorValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Value) GetEnum() *EnumValue {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Value) GetImage() *ImageValue {
	if x != nil {
		return x.Image
	}
	return nil
}

type BoolAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Perms         Permissions            `protobuf:"varint,2,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolAttribute) Reset() {
	*x = BoolAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolAttribute) ProtoMessage() {}

func (x *BoolAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolAttribute.ProtoReflect.Descriptor instead.
func (*BoolAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{13}
}

func (x *BoolAttribute) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *BoolAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type BoolValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolValue) Reset() {
	*x = BoolValue{}
	mi := &file_clients_client_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolValue) ProtoMessage() {}

func (x *BoolValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolValue.ProtoReflect.Descriptor instead.
func (*BoolValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{14}
}

func (x *BoolValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type IntAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`
	Min           int64                  `protobuf:"zigzag64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"zigzag64,3,opt,name=max,proto3" json:"max,omitempty"`
	Step          uint64                 `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	Unit          Unit                   `protobuf:"varint,5,opt,name=unit,proto3,enum=woodhouse.api.v1.clients.Unit" json:"unit,omitempty"`
	Perms         Permissions            `protobuf:"varint,6,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntAttribute) Reset() {
	*x = IntAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntAttribute) ProtoMessage() {}

func (x *IntAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntAttribute.ProtoReflect.Descriptor instead.
func (*IntAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{15}
}

func (x *IntAttribute) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntAttribute) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *IntAttribute) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *IntAttribute) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *IntAttribute) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNDEFINED
}

func (x *IntAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type IntValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntValue) Reset() {
	*x = IntValue{}
	mi := &file_clients_client_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntValue) ProtoMessage() {}

func (x *IntValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntValue.ProtoReflect.Descriptor instead.
func (*IntValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{16}
}

func (x *IntValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FloatAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Min           float64                `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Step          float64                `protobuf:"fixed64,4,opt,name=step,proto3" json:"step,omitempty"`
	Unit          Unit                   `protobuf:"varint,5,opt,name=unit,proto3,enum=woodhouse.api.v1.clients.Unit" json:"unit,omitempty"`
	Perms         Permissions            `protobuf:"varint,6,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatAttribute) Reset() {
	*x = FloatAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatAttribute) ProtoMessage() {}

func (x *FloatAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatAttribute.ProtoReflect.Descriptor instead.
func (*FloatAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{17}
}

func (x *FloatAttribute) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *FloatAttribute) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *FloatAttribute) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *FloatAttribute) GetStep() float64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *FloatAttribute) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNDEFINED
}

func (x *FloatAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type FloatValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatValue) Reset() {
	*x = FloatValue{}
	mi := &file_clients_client_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatValue) ProtoMessage() {}

func (x *FloatValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatValue.ProtoReflect.Descriptor instead.
func (*FloatValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{18}
}

func (x *FloatValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TextAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Perms         Permissions            `protobuf:"varint,2,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAttribute) Reset() {
	*x = TextAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAttribute) ProtoMessage() {}

func (x *TextAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAttribute.ProtoReflect.Descriptor instead.
func (*TextAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{19}
}

func (x *TextAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TextAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type TextValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextValue) Reset() {
	*x = TextValue{}
	mi := &file_clients_client_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextValue) ProtoMessage() {}

func (x *TextValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextValue.ProtoReflect.Descriptor instead.
func (*TextValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{20}
}

func (x *TextValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DurationAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"` // millis.
	Min           int64                  `protobuf:"zigzag64,2,opt,name=min,proto3" json:"min,omitempty"`     // millis.
	Max           int64                  `protobuf:"zigzag64,3,opt,name=max,proto3" json:"max,omitempty"`     // millis.
	Step          uint64                 `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`     // millis.
	Perms         Permissions            `protobuf:"varint,5,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationAttribute) Reset() {
	*x = DurationAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationAttribute) ProtoMessage() {}

func (x *DurationAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationAttribute.ProtoReflect.Descriptor instead.
func (*DurationAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{21}
}

func (x *DurationAttribute) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DurationAttribute) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DurationAttribute) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *DurationAttribute) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *DurationAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type DurationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"` // millis.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationValue) Reset() {
	*x = DurationValue{}
	mi := &file_clients_client_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationValue) ProtoMessage() {}

func (x *DurationValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationValue.ProtoReflect.Descriptor instead.
func (*DurationValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{22}
}

func (x *DurationValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TimeAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"zigzag64,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos         int32       `protobuf:"zigzag32,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	Perms         Permissions `protobuf:"varint,3,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeAttribute) Reset() {
	*x = TimeAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAttribute) ProtoMessage() {}

func (x *TimeAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAttribute.ProtoReflect.Descriptor instead.
func (*TimeAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{23}
}

func (x *TimeAttribute) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *TimeAttribute) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *TimeAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type TimeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"zigzag64,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos         int32 `protobuf:"zigzag32,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeValue) Reset() {
	*x = TimeValue{}
	mi := &file_clients_client_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeValue) ProtoMessage() {}

func (x *TimeValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeValue.ProtoReflect.Descriptor instead.
func (*TimeValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{24}
}

func (x *TimeValue) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *TimeValue) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type ColorAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HueSat        *ColorHueSat           `protobuf:"bytes,1,opt,name=hue_sat,json=hueSat,proto3" json:"hue_sat,omitempty"`
	Xy            *ColorXY               `protobuf:"bytes,2,opt,name=xy,proto3" json:"xy,omitempty"`
	Perms         Permissions            `protobuf:"varint,3,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorAttribute) Reset() {
	*x = ColorAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorAttribute) ProtoMessage() {}

func (x *ColorAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorAttribute.ProtoReflect.Descriptor instead.
func (*ColorAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{25}
}

func (x *ColorAttribute) GetHueSat() *ColorHueSat {
	if x != nil {
		return x.HueSat
	}
	return nil
}

func (x *ColorAttribute) GetXy() *ColorXY {
	if x != nil {
		return x.Xy
	}
	return nil
}

func (x *ColorAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type ColorValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HueSat        *ColorHueSat           `protobuf:"bytes,1,opt,name=hue_sat,json=hueSat,proto3" json:"hue_sat,omitempty"`
	Xy            *ColorXY               `protobuf:"bytes,2,opt,name=xy,proto3" json:"xy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorValue) Reset() {
	*x = ColorValue{}
	mi := &file_clients_client_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorValue) ProtoMessage() {}

func (x *ColorValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorValue.ProtoReflect.Descriptor instead.
func (*ColorValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{26}
}

func (x *ColorValue) GetHueSat() *ColorHueSat {
	if x != nil {
		return x.HueSat
	}
	return nil
}

func (x *ColorValue) GetXy() *ColorXY {
	if x != nil {
		return x.Xy
	}
	return nil
}

// Color expressed as hue/saturation.
type ColorHueSat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hue           float64                `protobuf:"fixed64,1,opt,name=hue,proto3" json:"hue,omitempty"`
	Sat           float64                `protobuf:"fixed64,2,opt,name=sat,proto3" json:"sat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorHueSat) Reset() {
	*x = ColorHueSat{}
	mi := &file_clients_client_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorHueSat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorHueSat) ProtoMessage() {}

func (x *ColorHueSat) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorHueSat.ProtoReflect.Descriptor instead.
func (*ColorHueSat) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{27}
}

func (x *ColorHueSat) GetHue() float64 {
	if x != nil {
		return x.Hue
	}
	return 0
}

func (x *ColorHueSat) GetSat() float64 {
	if x != nil {
		return x.Sat
	}
	return 0
}

// Color expressed in the CIE 1931 color space (x/y).
type ColorXY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorXY) Reset() {
	*x = ColorXY{}
	mi := &file_clients_client_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorXY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorXY) ProtoMessage() {}

func (x *ColorXY) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorXY.ProtoReflect.Descriptor instead.
func (*ColorXY) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{28}
}

func (x *ColorXY) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ColorXY) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type EnumAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Perms         Permissions            `protobuf:"varint,3,opt,name=perms,proto3,enum=woodhouse.api.v1.clients.Permissions" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumAttribute) Reset() {
	*x = EnumAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAttribute) ProtoMessage() {}

func (x *EnumAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAttribute.ProtoReflect.Descriptor instead.
func (*EnumAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{29}
}

func (x *EnumAttribute) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EnumAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumAttribute) GetPerms() Permissions {
	if x != nil {
		return x.Perms
	}
	return Permissions_PERM_UNDEFINED
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_clients_client_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{30}
}

func (x *EnumValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ImageAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageAttribute) Reset() {
	*x = ImageAttribute{}
	mi := &file_clients_client_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAttribute) ProtoMessage() {}

func (x *ImageAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageAttribute.ProtoReflect.Descriptor instead.
func (*ImageAttribute) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{31}
}

type ImageValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageValue) Reset() {
	*x = ImageValue{}
	mi := &file_clients_client_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageValue) ProtoMessage() {}

func (x *ImageValue) ProtoReflect() protoreflect.Message {
	mi := &file_clients_client_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageValue.ProtoReflect.Descriptor instead.
func (*ImageValue) Descriptor() ([]byte, []int) {
	return file_clients_client_service_proto_rawDescGZIP(), []int{32}
}

var File_clients_client_service_proto protoreflect.FileDescriptor

const file_clients_client_service_proto_rawDesc = "" +
	"\n" +
	"\x1cclients/client_service.proto\x12\x18woodhouse.api.v1.clients\"\a\n" +
	"\x05Empty\"\x98\x01\n" +
	"\fStatusUpdate\x12E\n" +
	"\vclient_info\x18\x01 \x01(\v2$.woodhouse.api.v1.clients.ClientInfoR\n" +
	"clientInfo\x12A\n" +
	"\vdevice_info\x18\x02 \x03(\v2 .woodhouse.api.v1.clients.DeviceR\n" +
	"deviceInfo\"\xa1\x01\n" +
	"\rActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x127\n" +
	"\x06values\x18\x04 \x03(\v2\x1f.woodhouse.api.v1.clients.ValueR\x06values\"\x91\x02\n" +
	"\x0eActionResponse\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12M\n" +
	"\x06status\x18\x02 \x01(\x0e25.woodhouse.api.v1.clients.ActionResponse.ActionStatusR\x06status\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"y\n" +
	"\fActionStatus\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\b\n" +
	"\x04SENT\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\x12\x10\n" +
	"\fERR_READONLY\x10\a\"l\n" +
	"\n" +
	"ClientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"9\n" +
	"\x13DeviceStreamRequest\x12\"\n" +
	"\rget_device_id\x18\x01 \x01(\tR\vgetDeviceId\"w\n" +
	"\x14DeviceStreamResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .woodhouse.api.v1.clients.DeviceR\x06device\x12%\n" +
	"\x0edevice_removed\x18\x02 \x01(\tR\rdeviceRemoved\"\x8c\x01\n" +
	"\fImageRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12!\n" +
	"\fattribute_id\x18\x04 \x01(\tR\vattributeId\"\x92\x02\n" +
	"\rImageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e23.woodhouse.api.v1.clients.ImageResponse.ImageStatusR\x06status\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"g\n" +
	"\vImageStatus\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04SENT\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\"\xa1\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"full_state\x18\x02 \x01(\bR\tfullState\x12=\n" +
	"\x03typ\x18\x03 \x01(\x0e2+.woodhouse.api.v1.clients.Device.DeviceTypeR\x03typ\x12=\n" +
	"\bservices\x18\x04 \x03(\v2!.woodhouse.api.v1.clients.ServiceR\bservices\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\"M\n" +
	"\n" +
	"DeviceType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\n" +
	"\n" +
	"\x06BRIDGE\x10\x01\x12\v\n" +
	"\aREACTOR\x10\x02\x12\n" +
	"\n" +
	"\x06DEVICE\x10\x03\x12\v\n" +
	"\aGROUPED\x10\x04\"\x84\x04\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x03typ\x18\x02 \x01(\x0e2-.woodhouse.api.v1.clients.Service.ServiceTypeR\x03typ\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x129\n" +
	"\x05attrs\x18\x04 \x03(\v2#.woodhouse.api.v1.clients.AttributeR\x05attrs\x12\x1a\n" +
	"\bfavorite\x18\x05 \x01(\bR\bfavorite\"\xba\x02\n" +
	"\vServiceType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x02\x12\v\n" +
	"\aGENERIC\x10\x03\x12\t\n" +
	"\x05INPUT\x10\x04\x12\t\n" +
	"\x05RELAY\x10\x05\x12\r\n" +
	"\tLIGHTBULB\x10\x06\x12\v\n" +
	"\aCLIMATE\x10\a\x12\v\n" +
	"\aBATTERY\x10\b\x12\n" +
	"\n" +
	"\x06BUTTON\x10\t\x12\x0f\n" +
	"\vENVIRONMENT\x10\n" +
	"\x12\v\n" +
	"\aCONTACT\x10\v\x12\n" +
	"\n" +
	"\x06UPDATE\x10\f\x12\b\n" +
	"\x04BOOL\x10\r\x12\a\n" +
	"\x03INT\x10\x0e\x12\t\n" +
	"\x05FLOAT\x10\x0f\x12\b\n" +
	"\x04TEXT\x10\x10\x12\f\n" +
	"\bDURATION\x10\x11\x12\b\n" +
	"\x04TIME\x10\x12\x12\t\n" +
	"\x05COLOR\x10\x13\x12\b\n" +
	"\x04ENUM\x10\x14\x12\n" +
	"\n" +
	"\x06CAMERA\x10\x15\x12\t\n" +
	"\x05COVER\x10\x16\x12\n" +
	"\n" +
	"\x06MOTION\x10\x17\x12\f\n" +
	"\bPRESENCE\x10\x18\"\xd2\x04\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x04bool\x18\x02 \x01(\v2'.woodhouse.api.v1.clients.BoolAttributeR\x04bool\x128\n" +
	"\x03int\x18\x03 \x01(\v2&.woodhouse.api.v1.clients.IntAttributeR\x03int\x12>\n" +
	"\x05float\x18\x04 \x01(\v2(.woodhouse.api.v1.clients.FloatAttributeR\x05float\x12;\n" +
	"\x04text\x18\x05 \x01(\v2'.woodhouse.api.v1.clients.TextAttributeR\x04text\x12G\n" +
	"\bduration\x18\a \x01(\v2+.woodhouse.api.v1.clients.DurationAttributeR\bduration\x12;\n" +
	"\x04time\x18\b \x01(\v2'.woodhouse.api.v1.clients.TimeAttributeR\x04time\x12>\n" +
	"\x05color\x18\n" +
	" \x01(\v2(.woodhouse.api.v1.clients.ColorAttributeR\x05color\x12;\n" +
	"\x04enum\x18\v \x01(\v2'.woodhouse.api.v1.clients.EnumAttributeR\x04enum\x12>\n" +
	"\x05image\x18\f \x01(\v2(.woodhouse.api.v1.clients.ImageAttributeR\x05image\"\xaa\x04\n" +
	"\x05Value\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04bool\x18\x02 \x01(\v2#.woodhouse.api.v1.clients.BoolValueR\x04bool\x124\n" +
	"\x03int\x18\x03 \x01(\v2\".woodhouse.api.v1.clients.IntValueR\x03int\x12:\n" +
	"\x05float\x18\x04 \x01(\v2$.woodhouse.api.v1.clients.FloatValueR\x05float\x127\n" +
	"\x04text\x18\x05 \x01(\v2#.woodhouse.api.v1.clients.TextValueR\x04text\x12C\n" +
	"\bduration\x18\a \x01(\v2'.woodhouse.api.v1.clients.DurationValueR\bduration\x127\n" +
	"\x04time\x18\b \x01(\v2#.woodhouse.api.v1.clients.TimeValueR\x04time\x12:\n" +
	"\x05color\x18\n" +
	" \x01(\v2$.woodhouse.api.v1.clients.ColorValueR\x05color\x127\n" +
	"\x04enum\x18\v \x01(\v2#.woodhouse.api.v1.clients.EnumValueR\x04enum\x12:\n" +
	"\x05image\x18\f \x01(\v2$.woodhouse.api.v1.clients.ImageValueR\x05image\"b\n" +
	"\rBoolAttribute\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12;\n" +
	"\x05perms\x18\x02 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"!\n" +
	"\tBoolValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"\xcd\x01\n" +
	"\fIntAttribute\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x12R\x05value\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x12R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x12R\x03max\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x04R\x04step\x122\n" +
	"\x04unit\x18\x05 \x01(\x0e2\x1e.woodhouse.api.v1.clients.UnitR\x04unit\x12;\n" +
	"\x05perms\x18\x06 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\" \n" +
	"\bIntValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x12R\x05value\"\xcf\x01\n" +
	"\x0eFloatAttribute\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x01R\x04step\x122\n" +
	"\x04unit\x18\x05 \x01(\x0e2\x1e.woodhouse.api.v1.clients.UnitR\x04unit\x12;\n" +
	"\x05perms\x18\x06 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"\"\n" +
	"\n" +
	"FloatValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"b\n" +
	"\rTextAttribute\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12;\n" +
	"\x05perms\x18\x02 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"!\n" +
	"\tTextValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x9e\x01\n" +
	"\x11DurationAttribute\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x12R\x05value\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x12R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x12R\x03max\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x04R\x04step\x12;\n" +
	"\x05perms\x18\x05 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"%\n" +
	"\rDurationValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x12R\x05value\"|\n" +
	"\rTimeAttribute\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x12R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x11R\x05nanos\x12;\n" +
	"\x05perms\x18\x03 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\";\n" +
	"\tTimeValue\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x12R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x11R\x05nanos\"\xc0\x01\n" +
	"\x0eColorAttribute\x12>\n" +
	"\ahue_sat\x18\x01 \x01(\v2%.woodhouse.api.v1.clients.ColorHueSatR\x06hueSat\x121\n" +
	"\x02xy\x18\x02 \x01(\v2!.woodhouse.api.v1.clients.ColorXYR\x02xy\x12;\n" +
	"\x05perms\x18\x03 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"\x7f\n" +
	"\n" +
	"ColorValue\x12>\n" +
	"\ahue_sat\x18\x01 \x01(\v2%.woodhouse.api.v1.clients.ColorHueSatR\x06hueSat\x121\n" +
	"\x02xy\x18\x02 \x01(\v2!.woodhouse.api.v1.clients.ColorXYR\x02xy\"1\n" +
	"\vColorHueSat\x12\x10\n" +
	"\x03hue\x18\x01 \x01(\x01R\x03hue\x12\x10\n" +
	"\x03sat\x18\x02 \x01(\x01R\x03sat\"%\n" +
	"\aColorXY\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"|\n" +
	"\rEnumAttribute\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12;\n" +
	"\x05perms\x18\x03 \x01(\x0e2%.woodhouse.api.v1.clients.PermissionsR\x05perms\"!\n" +
	"\tEnumValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x10\n" +
	"\x0eImageAttribute\"\f\n" +
	"\n" +
	"ImageValue*\\\n" +
	"\vPermissions\x12\x12\n" +
	"\x0ePERM_UNDEFINED\x10\x00\x12\x11\n" +
	"\rPERM_READONLY\x10\x01\x12\x12\n" +
	"\x0ePERM_WRITEONLY\x10\x02\x12\x12\n" +
	"\x0ePERM_READWRITE\x10\x03*\x91\x02\n" +
	"\x04Unit\x12\x12\n" +
	"\x0eUNIT_UNDEFINED\x10\x00\x12\x13\n" +
	"\x0fUNIT_PERCENTAGE\x10\x01\x12\x14\n" +
	"\x10UNIT_ARC_DEGREES\x10\x02\x12\x10\n" +
	"\fUNIT_CELSIUS\x10\x03\x12\f\n" +
	"\bUNIT_LUX\x10\x04\x12\x10\n" +
	"\fUNIT_SECONDS\x10\x05\x12\f\n" +
	"\bUNIT_PPM\x10\x06\x12#\n" +
	"\x1fUNIT_MICROGRAMS_PER_CUBIC_METER\x10\a\x12\x0e\n" +
	"\n" +
	"UNIT_VOLTS\x10\b\x12\r\n" +
	"\tUNIT_AMPS\x10\t\x12\x0e\n" +
	"\n" +
	"UNIT_WATTS\x10\n" +
	"\x12\x0f\n" +
	"\vUNIT_MIREDS\x10\v\x12\x14\n" +
	"\x10UNIT_HECTOPASCAL\x10\f\x12\x0f\n" +
	"\vUNIT_METERS\x10\r2\xf2\x04\n" +
	"\rClientService\x12Y\n" +
	"\fStatusStream\x12&.woodhouse.api.v1.clients.StatusUpdate\x1a\x1f.woodhouse.api.v1.clients.Empty(\x01\x12e\n" +
	"\fActionStream\x12(.woodhouse.api.v1.clients.ActionResponse\x1a'.woodhouse.api.v1.clients.ActionRequest(\x010\x01\x12b\n" +
	"\vImageStream\x12'.woodhouse.api.v1.clients.ImageResponse\x1a&.woodhouse.api.v1.clients.ImageRequest(\x010\x01\x12q\n" +
	"\fDeviceStream\x12-.woodhouse.api.v1.clients.DeviceStreamRequest\x1a..woodhouse.api.v1.clients.DeviceStreamResponse(\x010\x01\x12a\n" +
	"\n" +
	"SendAction\x12'.woodhouse.api.v1.clients.ActionRequest\x1a(.woodhouse.api.v1.clients.ActionResponse0\x01\x12e\n" +
	"\x10SendImageRequest\x12&.woodhouse.api.v1.clients.ImageRequest\x1a'.woodhouse.api.v1.clients.ImageResponse0\x01B=Z;github.com/jimjibone/woodhouse-api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_client_service_proto_rawDescOnce sync.Once
	file_clients_client_service_proto_rawDescData []byte
)

func file_clients_client_service_proto_rawDescGZIP() []byte {
	file_clients_client_service_proto_rawDescOnce.Do(func() {
		file_clients_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_client_service_proto_rawDesc), len(file_clients_client_service_proto_rawDesc)))
	})
	return file_clients_client_service_proto_rawDescData
}

var file_clients_client_service_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_clients_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_clients_client_service_proto_goTypes = []any{
	(Permissions)(0),                 // 0: woodhouse.api.v1.clients.Permissions
	(Unit)(0),                        // 1: woodhouse.api.v1.clients.Unit
	(ActionResponse_ActionStatus)(0), // 2: woodhouse.api.v1.clients.ActionResponse.ActionStatus
	(ImageResponse_ImageStatus)(0),   // 3: woodhouse.api.v1.clients.ImageResponse.ImageStatus
	(Device_DeviceType)(0),           // 4: woodhouse.api.v1.clients.Device.DeviceType
	(Service_ServiceType)(0),         // 5: woodhouse.api.v1.clients.Service.ServiceType
	(*Empty)(nil),                    // 6: woodhouse.api.v1.clients.Empty
	(*StatusUpdate)(nil),             // 7: woodhouse.api.v1.clients.StatusUpdate
	(*ActionRequest)(nil),            // 8: woodhouse.api.v1.clients.ActionRequest
	(*ActionResponse)(nil),           // 9: woodhouse.api.v1.clients.ActionResponse
	(*ClientInfo)(nil),               // 10: woodhouse.api.v1.clients.ClientInfo
	(*DeviceStreamRequest)(nil),      // 11: woodhouse.api.v1.clients.DeviceStreamRequest
	(*DeviceStreamResponse)(nil),     // 12: woodhouse.api.v1.clients.DeviceStreamResponse
	(*ImageRequest)(nil),             // 13: woodhouse.api.v1.clients.ImageRequest
	(*ImageResponse)(nil),            // 14: woodhouse.api.v1.clients.ImageResponse
	(*Device)(nil),                   // 15: woodhouse.api.v1.clients.Device
	(*Service)(nil),                  // 16: woodhouse.api.v1.clients.Service
	(*Attribute)(nil),                // 17: woodhouse.api.v1.clients.Attribute
	(*Value)(nil),                    // 18: woodhouse.api.v1.clients.Value
	(*BoolAttribute)(nil),            // 19: woodhouse.api.v1.clients.BoolAttribute
	(*BoolValue)(nil),                // 20: woodhouse.api.v1.clients.BoolValue
	(*IntAttribute)(nil),             // 21: woodhouse.api.v1.clients.IntAttribute
	(*IntValue)(nil),                 // 22: woodhouse.api.v1.clients.IntValue
	(*FloatAttribute)(nil),           // 23: woodhouse.api.v1.clients.FloatAttribute
	(*FloatValue)(nil),               // 24: woodhouse.api.v1.clients.FloatValue
	(*TextAttribute)(nil),            // 25: woodhouse.api.v1.clients.TextAttribute
	(*TextValue)(nil),                // 26: woodhouse.api.v1.clients.TextValue
	(*DurationAttribute)(nil),        // 27: woodhouse.api.v1.clients.DurationAttribute
	(*DurationValue)(nil),            // 28: woodhouse.api.v1.clients.DurationValue
	(*TimeAttribute)(nil),            // 29: woodhouse.api.v1.clients.TimeAttribute
	(*TimeValue)(nil),                // 30: woodhouse.api.v1.clients.TimeValue
	(*ColorAttribute)(nil),           // 31: woodhouse.api.v1.clients.ColorAttribute
	(*ColorValue)(nil),               // 32: woodhouse.api.v1.clients.ColorValue
	(*ColorHueSat)(nil),              // 33: woodhouse.api.v1.clients.ColorHueSat
	(*ColorXY)(nil),                  // 34: woodhouse.api.v1.clients.ColorXY
	(*EnumAttribute)(nil),            // 35: woodhouse.api.v1.clients.EnumAttribute
	(*EnumValue)(nil),                // 36: woodhouse.api.v1.clients.EnumValue
	(*ImageAttribute)(nil),           // 37: woodhouse.api.v1.clients.ImageAttribute
	(*ImageValue)(nil),               // 38: woodhouse.api.v1.clients.ImageValue
}
var file_clients_client_service_proto_depIdxs = []int32{
	10, // 0: woodhouse.api.v1.clients.StatusUpdate.client_info:type_name -> woodhouse.api.v1.clients.ClientInfo
	15, // 1: woodhouse.api.v1.clients.StatusUpdate.device_info:type_name -> woodhouse.api.v1.clients.Device
	18, // 2: woodhouse.api.v1.clients.ActionRequest.values:type_name -> woodhouse.api.v1.clients.Value
	2,  // 3: woodhouse.api.v1.clients.ActionResponse.status:type_name -> woodhouse.api.v1.clients.ActionResponse.ActionStatus
	15, // 4: woodhouse.api.v1.clients.DeviceStreamResponse.device:type_name -> woodhouse.api.v1.clients.Device
	3,  // 5: woodhouse.api.v1.clients.ImageResponse.status:type_name -> woodhouse.api.v1.clients.ImageResponse.ImageStatus
	4,  // 6: woodhouse.api.v1.clients.Device.typ:type_name -> woodhouse.api.v1.clients.Device.DeviceType
	16, // 7: woodhouse.api.v1.clients.Device.services:type_name -> woodhouse.api.v1.clients.Service
	5,  // 8: woodhouse.api.v1.clients.Service.typ:type_name -> woodhouse.api.v1.clients.Service.ServiceType
	17, // 9: woodhouse.api.v1.clients.Service.attrs:type_name -> woodhouse.api.v1.clients.Attribute
	19, // 10: woodhouse.api.v1.clients.Attribute.bool:type_name -> woodhouse.api.v1.clients.BoolAttribute
	21, // 11: woodhouse.api.v1.clients.Attribute.int:type_name -> woodhouse.api.v1.clients.IntAttribute
	23, // 12: woodhouse.api.v1.clients.Attribute.float:type_name -> woodhouse.api.v1.clients.FloatAttribute
	25, // 13: woodhouse.api.v1.clients.Attribute.text:type_name -> woodhouse.api.v1.clients.TextAttribute
	27, // 14: woodhouse.api.v1.clients.Attribute.duration:type_name -> woodhouse.api.v1.clients.DurationAttribute
	29, // 15: woodhouse.api.v1.clients.Attribute.time:type_name -> woodhouse.api.v1.clients.TimeAttribute
	31, // 16: woodhouse.api.v1.clients.Attribute.color:type_name -> woodhouse.api.v1.clients.ColorAttribute
	35, // 17: woodhouse.api.v1.clients.Attribute.enum:type_name -> woodhouse.api.v1.clients.EnumAttribute
	37, // 18: woodhouse.api.v1.clients.Attribute.image:type_name -> woodhouse.api.v1.clients.ImageAttribute
	20, // 19: woodhouse.api.v1.clients.Value.bool:type_name -> woodhouse.api.v1.clients.BoolValue
	22, // 20: woodhouse.api.v1.clients.Value.int:type_name -> woodhouse.api.v1.clients.IntValue
	24, // 21: woodhouse.api.v1.clients.Value.float:type_name -> woodhouse.api.v1.clients.FloatValue
	26, // 22: woodhouse.api.v1.clients.Value.text:type_name -> woodhouse.api.v1.clients.TextValue
	28, // 23: woodhouse.api.v1.clients.Value.duration:type_name -> woodhouse.api.v1.clients.DurationValue
	30, // 24: woodhouse.api.v1.clients.Value.time:type_name -> woodhouse.api.v1.clients.TimeValue
	32, // 25: woodhouse.api.v1.clients.Value.color:type_name -> woodhouse.api.v1.clients.ColorValue
	36, // 26: woodhouse.api.v1.clients.Value.enum:type_name -> woodhouse.api.v1.clients.EnumValue
	38, // 27: woodhouse.api.v1.clients.Value.image:type_name -> woodhouse.api.v1.clients.ImageValue
	0,  // 28: woodhouse.api.v1.clients.BoolAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	1,  // 29: woodhouse.api.v1.clients.IntAttribute.unit:type_name -> woodhouse.api.v1.clients.Unit
	0,  // 30: woodhouse.api.v1.clients.IntAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	1,  // 31: woodhouse.api.v1.clients.FloatAttribute.unit:type_name -> woodhouse.api.v1.clients.Unit
	0,  // 32: woodhouse.api.v1.clients.FloatAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	0,  // 33: woodhouse.api.v1.clients.TextAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	0,  // 34: woodhouse.api.v1.clients.DurationAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	0,  // 35: woodhouse.api.v1.clients.TimeAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	33, // 36: woodhouse.api.v1.clients.ColorAttribute.hue_sat:type_name -> woodhouse.api.v1.clients.ColorHueSat
	34, // 37: woodhouse.api.v1.clients.ColorAttribute.xy:type_name -> woodhouse.api.v1.clients.ColorXY
	0,  // 38: woodhouse.api.v1.clients.ColorAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	33, // 39: woodhouse.api.v1.clients.ColorValue.hue_sat:type_name -> woodhouse.api.v1.clients.ColorHueSat
	34, // 40: woodhouse.api.v1.clients.ColorValue.xy:type_name -> woodhouse.api.v1.clients.ColorXY
	0,  // 41: woodhouse.api.v1.clients.EnumAttribute.perms:type_name -> woodhouse.api.v1.clients.Permissions
	7,  // 42: woodhouse.api.v1.clients.ClientService.StatusStream:input_type -> woodhouse.api.v1.clients.StatusUpdate
	9,  // 43: woodhouse.api.v1.clients.ClientService.ActionStream:input_type -> woodhouse.api.v1.clients.ActionResponse
	14, // 44: woodhouse.api.v1.clients.ClientService.ImageStream:input_type -> woodhouse.api.v1.clients.ImageResponse
	11, // 45: woodhouse.api.v1.clients.ClientService.DeviceStream:input_type -> woodhouse.api.v1.clients.DeviceStreamRequest
	8,  // 46: woodhouse.api.v1.clients.ClientService.SendAction:input_type -> woodhouse.api.v1.clients.ActionRequest
	13, // 47: woodhouse.api.v1.clients.ClientService.SendImageRequest:input_type -> woodhouse.api.v1.clients.ImageRequest
	6,  // 48: woodhouse.api.v1.clients.ClientService.StatusStream:output_type -> woodhouse.api.v1.clients.Empty
	8,  // 49: woodhouse.api.v1.clients.ClientService.ActionStream:output_type -> woodhouse.api.v1.clients.ActionRequest
	13, // 50: woodhouse.api.v1.clients.ClientService.ImageStream:output_type -> woodhouse.api.v1.clients.ImageRequest
	12, // 51: woodhouse.api.v1.clients.ClientService.DeviceStream:output_type -> woodhouse.api.v1.clients.DeviceStreamResponse
	9,  // 52: woodhouse.api.v1.clients.ClientService.SendAction:output_type -> woodhouse.api.v1.clients.ActionResponse
	14, // 53: woodhouse.api.v1.clients.ClientService.SendImageRequest:output_type -> woodhouse.api.v1.clients.ImageResponse
	48, // [48:54] is the sub-list for method output_type
	42, // [42:48] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_clients_client_service_proto_init() }
func file_clients_client_service_proto_init() {
	if File_clients_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_client_service_proto_rawDesc), len(file_clients_client_service_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_client_service_proto_goTypes,
		DependencyIndexes: file_clients_client_service_proto_depIdxs,
		EnumInfos:         file_clients_client_service_proto_enumTypes,
		MessageInfos:      file_clients_client_service_proto_msgTypes,
	}.Build()
	File_clients_client_service_proto = out.File
	file_clients_client_service_proto_goTypes = nil
	file_clients_client_service_proto_depIdxs = nil
}
