// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: clients/group.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                        // The universally unique device ID (typically a UUID or other static and unique identifier, e.g. "00158d00045c089f").
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                         // The service ID (typically the name of the service type, e.g. "info").
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                    // The name of this group.
	Type          Service_ServiceType    `protobuf:"varint,4,opt,name=type,proto3,enum=woodhouse.api.v1.clients.Service_ServiceType" json:"type,omitempty"` // The service type. All members of the group must have the same service type.
	Members       []*GroupMember         `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`                                              // The group members.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_clients_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_clients_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_clients_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetType() Service_ServiceType {
	if x != nil {
		return x.Type
	}
	return Service_UNDEFINED
}

func (x *Group) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`    // The universally unique device ID (typically a hardware address or other static and unique identifier, e.g. "00158d00045c089f").
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // The service ID (typically the name of the service type, e.g. "info").
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_clients_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_clients_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_clients_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GroupMember) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

var File_clients_group_proto protoreflect.FileDescriptor

const file_clients_group_proto_rawDesc = "" +
	"\n" +
	"\x13clients/group.proto\x12\x18woodhouse.api.v1.clients\x1a\x1cclients/client_service.proto\"\xce\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12A\n" +
	"\x04type\x18\x04 \x01(\x0e2-.woodhouse.api.v1.clients.Service.ServiceTypeR\x04type\x12?\n" +
	"\amembers\x18\x05 \x03(\v2%.woodhouse.api.v1.clients.GroupMemberR\amembers\"I\n" +
	"\vGroupMember\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceIdB?Z=github.com/jimjibone/woodhouse-4/api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_group_proto_rawDescOnce sync.Once
	file_clients_group_proto_rawDescData []byte
)

func file_clients_group_proto_rawDescGZIP() []byte {
	file_clients_group_proto_rawDescOnce.Do(func() {
		file_clients_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_group_proto_rawDesc), len(file_clients_group_proto_rawDesc)))
	})
	return file_clients_group_proto_rawDescData
}

var file_clients_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clients_group_proto_goTypes = []any{
	(*Group)(nil),            // 0: woodhouse.api.v1.clients.Group
	(*GroupMember)(nil),      // 1: woodhouse.api.v1.clients.GroupMember
	(Service_ServiceType)(0), // 2: woodhouse.api.v1.clients.Service.ServiceType
}
var file_clients_group_proto_depIdxs = []int32{
	2, // 0: woodhouse.api.v1.clients.Group.type:type_name -> woodhouse.api.v1.clients.Service.ServiceType
	1, // 1: woodhouse.api.v1.clients.Group.members:type_name -> woodhouse.api.v1.clients.GroupMember
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_clients_group_proto_init() }
func file_clients_group_proto_init() {
	if File_clients_group_proto != nil {
		return
	}
	file_clients_client_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_group_proto_rawDesc), len(file_clients_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clients_group_proto_goTypes,
		DependencyIndexes: file_clients_group_proto_depIdxs,
		MessageInfos:      file_clients_group_proto_msgTypes,
	}.Build()
	File_clients_group_proto = out.File
	file_clients_group_proto_goTypes = nil
	file_clients_group_proto_depIdxs = nil
}
