// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: clients/user_service.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNDEFINED UserRole = 0
	UserRole_USER_ROLE_ADMIN     UserRole = 1
	UserRole_USER_ROLE_USER      UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNDEFINED",
		1: "USER_ROLE_ADMIN",
		2: "USER_ROLE_USER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNDEFINED": 0,
		"USER_ROLE_ADMIN":     1,
		"USER_ROLE_USER":      2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_clients_user_service_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_clients_user_service_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{0}
}

type GetClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientsRequest) Reset() {
	*x = GetClientsRequest{}
	mi := &file_clients_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientsRequest) ProtoMessage() {}

func (x *GetClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientsRequest.ProtoReflect.Descriptor instead.
func (*GetClientsRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{0}
}

type ClientsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsStreamRequest) Reset() {
	*x = ClientsStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsStreamRequest) ProtoMessage() {}

func (x *ClientsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientsStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{1}
}

type ClientsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`                                    // Optional: A client update, possibly containing the full state.
	ClientRemoved string                 `protobuf:"bytes,2,opt,name=client_removed,json=clientRemoved,proto3" json:"client_removed,omitempty"` // Optional: Indicates the client_id of a client that was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsStreamResponse) Reset() {
	*x = ClientsStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsStreamResponse) ProtoMessage() {}

func (x *ClientsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientsStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *ClientsStreamResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ClientsStreamResponse) GetClientRemoved() string {
	if x != nil {
		return x.ClientRemoved
	}
	return ""
}

type PairingRequestsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequestsStreamRequest) Reset() {
	*x = PairingRequestsStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequestsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequestsStreamRequest) ProtoMessage() {}

func (x *PairingRequestsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequestsStreamRequest.ProtoReflect.Descriptor instead.
func (*PairingRequestsStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{3}
}

type PairingRequestsStreamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PairingRequest *PairingRequest        `protobuf:"bytes,1,opt,name=pairing_request,json=pairingRequest,proto3" json:"pairing_request,omitempty"` // Optional: A pairing request update, possibly containing the full state.
	PairingRemoved string                 `protobuf:"bytes,2,opt,name=pairing_removed,json=pairingRemoved,proto3" json:"pairing_removed,omitempty"` // Optional: Indicates the client_id of a pairing request that was removed.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PairingRequestsStreamResponse) Reset() {
	*x = PairingRequestsStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequestsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequestsStreamResponse) ProtoMessage() {}

func (x *PairingRequestsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequestsStreamResponse.ProtoReflect.Descriptor instead.
func (*PairingRequestsStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *PairingRequestsStreamResponse) GetPairingRequest() *PairingRequest {
	if x != nil {
		return x.PairingRequest
	}
	return nil
}

func (x *PairingRequestsStreamResponse) GetPairingRemoved() string {
	if x != nil {
		return x.PairingRemoved
	}
	return ""
}

type ApprovePairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PairingCode   string                 `protobuf:"bytes,2,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePairingRequest) Reset() {
	*x = ApprovePairingRequest{}
	mi := &file_clients_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePairingRequest) ProtoMessage() {}

func (x *ApprovePairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePairingRequest.ProtoReflect.Descriptor instead.
func (*ApprovePairingRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovePairingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ApprovePairingRequest) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

type ApprovePairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePairingResponse) Reset() {
	*x = ApprovePairingResponse{}
	mi := &file_clients_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePairingResponse) ProtoMessage() {}

func (x *ApprovePairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePairingResponse.ProtoReflect.Descriptor instead.
func (*ApprovePairingResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{6}
}

type DenyPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyPairingRequest) Reset() {
	*x = DenyPairingRequest{}
	mi := &file_clients_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyPairingRequest) ProtoMessage() {}

func (x *DenyPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyPairingRequest.ProtoReflect.Descriptor instead.
func (*DenyPairingRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *DenyPairingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DenyPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyPairingResponse) Reset() {
	*x = DenyPairingResponse{}
	mi := &file_clients_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyPairingResponse) ProtoMessage() {}

func (x *DenyPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyPairingResponse.ProtoReflect.Descriptor instead.
func (*DenyPairingResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{8}
}

type UnpairClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpairClientRequest) Reset() {
	*x = UnpairClientRequest{}
	mi := &file_clients_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpairClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpairClientRequest) ProtoMessage() {}

func (x *UnpairClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpairClientRequest.ProtoReflect.Descriptor instead.
func (*UnpairClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnpairClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type UnpairClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpairClientResponse) Reset() {
	*x = UnpairClientResponse{}
	mi := &file_clients_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpairClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpairClientResponse) ProtoMessage() {}

func (x *UnpairClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpairClientResponse.ProtoReflect.Descriptor instead.
func (*UnpairClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{10}
}

type ForgetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetClientRequest) Reset() {
	*x = ForgetClientRequest{}
	mi := &file_clients_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetClientRequest) ProtoMessage() {}

func (x *ForgetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetClientRequest.ProtoReflect.Descriptor instead.
func (*ForgetClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *ForgetClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ForgetClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetClientResponse) Reset() {
	*x = ForgetClientResponse{}
	mi := &file_clients_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetClientResponse) ProtoMessage() {}

func (x *ForgetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetClientResponse.ProtoReflect.Descriptor instead.
func (*ForgetClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{12}
}

type GetDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	mi := &file_clients_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{13}
}

type DevicesStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of device IDs to include in the steam. Sends all devices if empty.
	IncludeDeviceIds []string `protobuf:"bytes,1,rep,name=include_device_ids,json=includeDeviceIds,proto3" json:"include_device_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DevicesStreamRequest) Reset() {
	*x = DevicesStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesStreamRequest) ProtoMessage() {}

func (x *DevicesStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesStreamRequest.ProtoReflect.Descriptor instead.
func (*DevicesStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *DevicesStreamRequest) GetIncludeDeviceIds() []string {
	if x != nil {
		return x.IncludeDeviceIds
	}
	return nil
}

type DevicesStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                                    // Optional: A device update, possibly containing the full state.
	DeviceRemoved string                 `protobuf:"bytes,2,opt,name=device_removed,json=deviceRemoved,proto3" json:"device_removed,omitempty"` // Optional: Indicates the device_id of a device that was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesStreamResponse) Reset() {
	*x = DevicesStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesStreamResponse) ProtoMessage() {}

func (x *DevicesStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesStreamResponse.ProtoReflect.Descriptor instead.
func (*DevicesStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *DevicesStreamResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DevicesStreamResponse) GetDeviceRemoved() string {
	if x != nil {
		return x.DeviceRemoved
	}
	return ""
}

type RemoveDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceRequest) Reset() {
	*x = RemoveDeviceRequest{}
	mi := &file_clients_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceRequest) ProtoMessage() {}

func (x *RemoveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceRequest.ProtoReflect.Descriptor instead.
func (*RemoveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RemoveDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceResponse) Reset() {
	*x = RemoveDeviceResponse{}
	mi := &file_clients_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceResponse) ProtoMessage() {}

func (x *RemoveDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceResponse.ProtoReflect.Descriptor instead.
func (*RemoveDeviceResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{17}
}

type DeviceService struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                               // The key is a combined version of the device and service IDs.
	DeviceId  string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`     // The universally unique device ID (typically a hardware address or other static and unique identifier, e.g. "00158d00045c089f").
	FullState bool                   `protobuf:"varint,3,opt,name=full_state,json=fullState,proto3" json:"full_state,omitempty"` // Indicates that this message contains the entire state of the device.
	// The device name from the info service. May not be set if the value has not changed and full_state is false.
	DeviceName *string `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3,oneof" json:"device_name,omitempty"`
	// The device online state from the online service. May not be set if the value has not changed and full_state is
	// false.
	Online *bool `protobuf:"varint,7,opt,name=online,proto3,oneof" json:"online,omitempty"`
	// The device last seen time from the online service. May not be set if the last_seen value has not changed and
	// full_state is false.
	LastSeen *TimeValue `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3,oneof" json:"last_seen,omitempty"`
	// The device battery level state from the battery service. May not be set if the battery_level value has not
	// changed and full_state is false, or if the device does not have the battery service.
	BatteryLevel  *int64   `protobuf:"varint,11,opt,name=battery_level,json=batteryLevel,proto3,oneof" json:"battery_level,omitempty"`
	Service       *Service `protobuf:"bytes,12,opt,name=service,proto3" json:"service,omitempty"` // A service belonging to the device.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceService) Reset() {
	*x = DeviceService{}
	mi := &file_clients_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceService) ProtoMessage() {}

func (x *DeviceService) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceService.ProtoReflect.Descriptor instead.
func (*DeviceService) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeviceService) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceService) GetFullState() bool {
	if x != nil {
		return x.FullState
	}
	return false
}

func (x *DeviceService) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *DeviceService) GetOnline() bool {
	if x != nil && x.Online != nil {
		return *x.Online
	}
	return false
}

func (x *DeviceService) GetLastSeen() *TimeValue {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *DeviceService) GetBatteryLevel() int64 {
	if x != nil && x.BatteryLevel != nil {
		return *x.BatteryLevel
	}
	return 0
}

func (x *DeviceService) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type FavoritesStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoritesStreamRequest) Reset() {
	*x = FavoritesStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoritesStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoritesStreamRequest) ProtoMessage() {}

func (x *FavoritesStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoritesStreamRequest.ProtoReflect.Descriptor instead.
func (*FavoritesStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{19}
}

type FavoritesStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceService *DeviceService         `protobuf:"bytes,1,opt,name=device_service,json=deviceService,proto3" json:"device_service,omitempty"` // Optional: A DeviceService update, possibly containing the full state.
	KeyRemoved    string                 `protobuf:"bytes,2,opt,name=key_removed,json=keyRemoved,proto3" json:"key_removed,omitempty"`          // Optional: Indicates the key of a DeviceService that was was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoritesStreamResponse) Reset() {
	*x = FavoritesStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoritesStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoritesStreamResponse) ProtoMessage() {}

func (x *FavoritesStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoritesStreamResponse.ProtoReflect.Descriptor instead.
func (*FavoritesStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{20}
}

func (x *FavoritesStreamResponse) GetDeviceService() *DeviceService {
	if x != nil {
		return x.DeviceService
	}
	return nil
}

func (x *FavoritesStreamResponse) GetKeyRemoved() string {
	if x != nil {
		return x.KeyRemoved
	}
	return ""
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_clients_user_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{21}
}

func (x *AddFavoriteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AddFavoriteRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_clients_user_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{22}
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_clients_user_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveFavoriteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RemoveFavoriteRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RemoveFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_clients_user_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{24}
}

type GroupsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsStreamRequest) Reset() {
	*x = GroupsStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsStreamRequest) ProtoMessage() {}

func (x *GroupsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsStreamRequest.ProtoReflect.Descriptor instead.
func (*GroupsStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{25}
}

type GroupsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupUpdate   *Group                 `protobuf:"bytes,1,opt,name=group_update,json=groupUpdate,proto3" json:"group_update,omitempty"` // Optional: A Group update.
	RemovedId     string                 `protobuf:"bytes,2,opt,name=removed_id,json=removedId,proto3" json:"removed_id,omitempty"`       // Optional: Indicates the group ID of a Group that was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsStreamResponse) Reset() {
	*x = GroupsStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsStreamResponse) ProtoMessage() {}

func (x *GroupsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsStreamResponse.ProtoReflect.Descriptor instead.
func (*GroupsStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{26}
}

func (x *GroupsStreamResponse) GetGroupUpdate() *Group {
	if x != nil {
		return x.GroupUpdate
	}
	return nil
}

func (x *GroupsStreamResponse) GetRemovedId() string {
	if x != nil {
		return x.RemovedId
	}
	return ""
}

type AddGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          Service_ServiceType    `protobuf:"varint,2,opt,name=type,proto3,enum=woodhouse.api.v1.clients.Service_ServiceType" json:"type,omitempty"`
	Members       []*GroupMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupRequest) Reset() {
	*x = AddGroupRequest{}
	mi := &file_clients_user_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest) ProtoMessage() {}

func (x *AddGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest.ProtoReflect.Descriptor instead.
func (*AddGroupRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{27}
}

func (x *AddGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGroupRequest) GetType() Service_ServiceType {
	if x != nil {
		return x.Type
	}
	return Service_UNDEFINED
}

func (x *AddGroupRequest) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // The added group, including the generated ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupResponse) Reset() {
	*x = AddGroupResponse{}
	mi := &file_clients_user_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupResponse) ProtoMessage() {}

func (x *AddGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupResponse.ProtoReflect.Descriptor instead.
func (*AddGroupResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{28}
}

func (x *AddGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"` // Optional: If not set, the name will not be updated.
	Members       []*GroupMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"` // The full list of members for the group. If empty, the members will not be updated.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_clients_user_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_clients_user_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{30}
}

type RemoveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupRequest) Reset() {
	*x = RemoveGroupRequest{}
	mi := &file_clients_user_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupRequest) ProtoMessage() {}

func (x *RemoveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupResponse) Reset() {
	*x = RemoveGroupResponse{}
	mi := &file_clients_user_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupResponse) ProtoMessage() {}

func (x *RemoveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveGroupResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{32}
}

type UsersStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersStreamRequest) Reset() {
	*x = UsersStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersStreamRequest) ProtoMessage() {}

func (x *UsersStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersStreamRequest.ProtoReflect.Descriptor instead.
func (*UsersStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{33}
}

type UsersStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                                  // Optional: A User update, possibly containing the full state.
	UserRemoved   string                 `protobuf:"bytes,2,opt,name=user_removed,json=userRemoved,proto3" json:"user_removed,omitempty"` // Optional: Indicates the key of a User that was removed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersStreamResponse) Reset() {
	*x = UsersStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersStreamResponse) ProtoMessage() {}

func (x *UsersStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersStreamResponse.ProtoReflect.Descriptor instead.
func (*UsersStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{34}
}

func (x *UsersStreamResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UsersStreamResponse) GetUserRemoved() string {
	if x != nil {
		return x.UserRemoved
	}
	return ""
}

type AddUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname        string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Role            UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=woodhouse.api.v1.clients.UserRole" json:"role,omitempty"`
	InitialPassword string                 `protobuf:"bytes,4,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_clients_user_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{35}
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *AddUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNDEFINED
}

func (x *AddUserRequest) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_clients_user_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{36}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      *string                `protobuf:"bytes,2,opt,name=fullname,proto3,oneof" json:"fullname,omitempty"`
	Role          *UserRole              `protobuf:"varint,3,opt,name=role,proto3,enum=woodhouse.api.v1.clients.UserRole,oneof" json:"role,omitempty"`
	Password      *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_clients_user_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetFullname() string {
	if x != nil && x.Fullname != nil {
		return *x.Fullname
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() UserRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return UserRole_USER_ROLE_UNDEFINED
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_clients_user_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{38}
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_clients_user_service_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{39}
}

func (x *RemoveUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemoveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserResponse) Reset() {
	*x = RemoveUserResponse{}
	mi := &file_clients_user_service_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserResponse) ProtoMessage() {}

func (x *RemoveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{40}
}

type ImagesStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of device IDs to subscribe to. Subscribes to all cameras if empty.
	DeviceIds []string `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	// Per-camera size hints. The server uses the maximum width/height seen
	// across all connected subscribers when resizing cached images.
	SizeHints     []*ImageSizeHint `protobuf:"bytes,2,rep,name=size_hints,json=sizeHints,proto3" json:"size_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagesStreamRequest) Reset() {
	*x = ImagesStreamRequest{}
	mi := &file_clients_user_service_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagesStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesStreamRequest) ProtoMessage() {}

func (x *ImagesStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesStreamRequest.ProtoReflect.Descriptor instead.
func (*ImagesStreamRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{41}
}

func (x *ImagesStreamRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *ImagesStreamRequest) GetSizeHints() []*ImageSizeHint {
	if x != nil {
		return x.SizeHints
	}
	return nil
}

// ImageSizeHint tells the server the rendered pixel size of a specific camera
// attribute so it can resize the cached image to the appropriate resolution.
type ImageSizeHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,3,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`   // Rendered pixel width.  0 = full resolution.
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"` // Rendered pixel height. 0 = full resolution.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSizeHint) Reset() {
	*x = ImageSizeHint{}
	mi := &file_clients_user_service_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSizeHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSizeHint) ProtoMessage() {}

func (x *ImageSizeHint) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSizeHint.ProtoReflect.Descriptor instead.
func (*ImageSizeHint) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{42}
}

func (x *ImageSizeHint) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ImageSizeHint) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ImageSizeHint) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *ImageSizeHint) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageSizeHint) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// UserImageRequest is like ImageRequest but with an optional size hint for
// server-side resizing. The size hint is not forwarded to the bridge.
type UserImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,3,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`   // Desired pixel width.  0 = full resolution.
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"` // Desired pixel height. 0 = full resolution.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserImageRequest) Reset() {
	*x = UserImageRequest{}
	mi := &file_clients_user_service_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserImageRequest) ProtoMessage() {}

func (x *UserImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserImageRequest.ProtoReflect.Descriptor instead.
func (*UserImageRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{43}
}

func (x *UserImageRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UserImageRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UserImageRequest) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *UserImageRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserImageRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ImagesStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,3,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FetchedAt     int64                  `protobuf:"varint,6,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"` // Unix milliseconds.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagesStreamResponse) Reset() {
	*x = ImagesStreamResponse{}
	mi := &file_clients_user_service_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagesStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesStreamResponse) ProtoMessage() {}

func (x *ImagesStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesStreamResponse.ProtoReflect.Descriptor instead.
func (*ImagesStreamResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{44}
}

func (x *ImagesStreamResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ImagesStreamResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ImagesStreamResponse) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *ImagesStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImagesStreamResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImagesStreamResponse) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=woodhouse.api.v1.clients.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_clients_user_service_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_service_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_clients_user_service_proto_rawDescGZIP(), []int{45}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNDEFINED
}

var File_clients_user_service_proto protoreflect.FileDescriptor

const file_clients_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1aclients/user_service.proto\x12\x18woodhouse.api.v1.clients\x1a\x14clients/client.proto\x1a\x1cclients/client_service.proto\x1a\x13clients/group.proto\"\x13\n" +
	"\x11GetClientsRequest\"\x16\n" +
	"\x14ClientsStreamRequest\"x\n" +
	"\x15ClientsStreamResponse\x128\n" +
	"\x06client\x18\x01 \x01(\v2 .woodhouse.api.v1.clients.ClientR\x06client\x12%\n" +
	"\x0eclient_removed\x18\x02 \x01(\tR\rclientRemoved\"\x1e\n" +
	"\x1cPairingRequestsStreamRequest\"\x9b\x01\n" +
	"\x1dPairingRequestsStreamResponse\x12Q\n" +
	"\x0fpairing_request\x18\x01 \x01(\v2(.woodhouse.api.v1.clients.PairingRequestR\x0epairingRequest\x12'\n" +
	"\x0fpairing_removed\x18\x02 \x01(\tR\x0epairingRemoved\"W\n" +
	"\x15ApprovePairingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fpairing_code\x18\x02 \x01(\tR\vpairingCode\"\x18\n" +
	"\x16ApprovePairingResponse\"1\n" +
	"\x12DenyPairingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x15\n" +
	"\x13DenyPairingResponse\"2\n" +
	"\x13UnpairClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x16\n" +
	"\x14UnpairClientResponse\"2\n" +
	"\x13ForgetClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x16\n" +
	"\x14ForgetClientResponse\"\x13\n" +
	"\x11GetDevicesRequest\"D\n" +
	"\x14DevicesStreamRequest\x12,\n" +
	"\x12include_device_ids\x18\x01 \x03(\tR\x10includeDeviceIds\"x\n" +
	"\x15DevicesStreamResponse\x128\n" +
	"\x06device\x18\x01 \x01(\v2 .woodhouse.api.v1.clients.DeviceR\x06device\x12%\n" +
	"\x0edevice_removed\x18\x02 \x01(\tR\rdeviceRemoved\"2\n" +
	"\x13RemoveDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x16\n" +
	"\x14RemoveDeviceResponse\"\x89\x03\n" +
	"\rDeviceService\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"full_state\x18\x03 \x01(\bR\tfullState\x12$\n" +
	"\vdevice_name\x18\x05 \x01(\tH\x00R\n" +
	"deviceName\x88\x01\x01\x12\x1b\n" +
	"\x06online\x18\a \x01(\bH\x01R\x06online\x88\x01\x01\x12E\n" +
	"\tlast_seen\x18\t \x01(\v2#.woodhouse.api.v1.clients.TimeValueH\x02R\blastSeen\x88\x01\x01\x12(\n" +
	"\rbattery_level\x18\v \x01(\x03H\x03R\fbatteryLevel\x88\x01\x01\x12;\n" +
	"\aservice\x18\f \x01(\v2!.woodhouse.api.v1.clients.ServiceR\aserviceB\x0e\n" +
	"\f_device_nameB\t\n" +
	"\a_onlineB\f\n" +
	"\n" +
	"_last_seenB\x10\n" +
	"\x0e_battery_level\"\x18\n" +
	"\x16FavoritesStreamRequest\"\x8a\x01\n" +
	"\x17FavoritesStreamResponse\x12N\n" +
	"\x0edevice_service\x18\x01 \x01(\v2'.woodhouse.api.v1.clients.DeviceServiceR\rdeviceService\x12\x1f\n" +
	"\vkey_removed\x18\x02 \x01(\tR\n" +
	"keyRemoved\"P\n" +
	"\x12AddFavoriteRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"\x15\n" +
	"\x13AddFavoriteResponse\"S\n" +
	"\x15RemoveFavoriteRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"\x18\n" +
	"\x16RemoveFavoriteResponse\"\x15\n" +
	"\x13GroupsStreamRequest\"y\n" +
	"\x14GroupsStreamResponse\x12B\n" +
	"\fgroup_update\x18\x01 \x01(\v2\x1f.woodhouse.api.v1.clients.GroupR\vgroupUpdate\x12\x1d\n" +
	"\n" +
	"removed_id\x18\x02 \x01(\tR\tremovedId\"\xa9\x01\n" +
	"\x0fAddGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x04type\x18\x02 \x01(\x0e2-.woodhouse.api.v1.clients.Service.ServiceTypeR\x04type\x12?\n" +
	"\amembers\x18\x03 \x03(\v2%.woodhouse.api.v1.clients.GroupMemberR\amembers\"I\n" +
	"\x10AddGroupResponse\x125\n" +
	"\x05group\x18\x01 \x01(\v2\x1f.woodhouse.api.v1.clients.GroupR\x05group\"\x87\x01\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12?\n" +
	"\amembers\x18\x03 \x03(\v2%.woodhouse.api.v1.clients.GroupMemberR\amembersB\a\n" +
	"\x05_name\"\x15\n" +
	"\x13UpdateGroupResponse\"$\n" +
	"\x12RemoveGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13RemoveGroupResponse\"\x14\n" +
	"\x12UsersStreamRequest\"l\n" +
	"\x13UsersStreamResponse\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.woodhouse.api.v1.clients.UserR\x04user\x12!\n" +
	"\fuser_removed\x18\x02 \x01(\tR\vuserRemoved\"\xab\x01\n" +
	"\x0eAddUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x126\n" +
	"\x04role\x18\x03 \x01(\x0e2\".woodhouse.api.v1.clients.UserRoleR\x04role\x12)\n" +
	"\x10initial_password\x18\x04 \x01(\tR\x0finitialPassword\"\x11\n" +
	"\x0fAddUserResponse\"\xd1\x01\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\bfullname\x18\x02 \x01(\tH\x00R\bfullname\x88\x01\x01\x12;\n" +
	"\x04role\x18\x03 \x01(\x0e2\".woodhouse.api.v1.clients.UserRoleH\x01R\x04role\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x02R\bpassword\x88\x01\x01B\v\n" +
	"\t_fullnameB\a\n" +
	"\x05_roleB\v\n" +
	"\t_password\"\x14\n" +
	"\x12UpdateUserResponse\"/\n" +
	"\x11RemoveUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x14\n" +
	"\x12RemoveUserResponse\"|\n" +
	"\x13ImagesStreamRequest\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\x12F\n" +
	"\n" +
	"size_hints\x18\x02 \x03(\v2'.woodhouse.api.v1.clients.ImageSizeHintR\tsizeHints\"\x9c\x01\n" +
	"\rImageSizeHint\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fattribute_id\x18\x03 \x01(\tR\vattributeId\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\"\x9f\x01\n" +
	"\x10UserImageRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fattribute_id\x18\x03 \x01(\tR\vattributeId\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\"\xc5\x01\n" +
	"\x14ImagesStreamResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fattribute_id\x18\x03 \x01(\tR\vattributeId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\x06 \x01(\x03R\tfetchedAt\"v\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x126\n" +
	"\x04role\x18\x03 \x01(\x0e2\".woodhouse.api.v1.clients.UserRoleR\x04role*L\n" +
	"\bUserRole\x12\x17\n" +
	"\x13USER_ROLE_UNDEFINED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x022\xd4\x14\n" +
	"\vUserService\x12]\n" +
	"\n" +
	"GetClients\x12+.woodhouse.api.v1.clients.GetClientsRequest\x1a .woodhouse.api.v1.clients.Client0\x01\x12r\n" +
	"\rClientsStream\x12..woodhouse.api.v1.clients.ClientsStreamRequest\x1a/.woodhouse.api.v1.clients.ClientsStreamResponse0\x01\x12\x8a\x01\n" +
	"\x15PairingRequestsStream\x126.woodhouse.api.v1.clients.PairingRequestsStreamRequest\x1a7.woodhouse.api.v1.clients.PairingRequestsStreamResponse0\x01\x12s\n" +
	"\x0eApprovePairing\x12/.woodhouse.api.v1.clients.ApprovePairingRequest\x1a0.woodhouse.api.v1.clients.ApprovePairingResponse\x12j\n" +
	"\vDenyPairing\x12,.woodhouse.api.v1.clients.DenyPairingRequest\x1a-.woodhouse.api.v1.clients.DenyPairingResponse\x12m\n" +
	"\fUnpairClient\x12-.woodhouse.api.v1.clients.UnpairClientRequest\x1a..woodhouse.api.v1.clients.UnpairClientResponse\x12m\n" +
	"\fForgetClient\x12-.woodhouse.api.v1.clients.ForgetClientRequest\x1a..woodhouse.api.v1.clients.ForgetClientResponse\x12]\n" +
	"\n" +
	"GetDevices\x12+.woodhouse.api.v1.clients.GetDevicesRequest\x1a .woodhouse.api.v1.clients.Device0\x01\x12r\n" +
	"\rDevicesStream\x12..woodhouse.api.v1.clients.DevicesStreamRequest\x1a/.woodhouse.api.v1.clients.DevicesStreamResponse0\x01\x12m\n" +
	"\fRemoveDevice\x12-.woodhouse.api.v1.clients.RemoveDeviceRequest\x1a..woodhouse.api.v1.clients.RemoveDeviceResponse\x12x\n" +
	"\x0fFavoritesStream\x120.woodhouse.api.v1.clients.FavoritesStreamRequest\x1a1.woodhouse.api.v1.clients.FavoritesStreamResponse0\x01\x12j\n" +
	"\vAddFavorite\x12,.woodhouse.api.v1.clients.AddFavoriteRequest\x1a-.woodhouse.api.v1.clients.AddFavoriteResponse\x12s\n" +
	"\x0eRemoveFavorite\x12/.woodhouse.api.v1.clients.RemoveFavoriteRequest\x1a0.woodhouse.api.v1.clients.RemoveFavoriteResponse\x12o\n" +
	"\fGroupsStream\x12-.woodhouse.api.v1.clients.GroupsStreamRequest\x1a..woodhouse.api.v1.clients.GroupsStreamResponse0\x01\x12a\n" +
	"\bAddGroup\x12).woodhouse.api.v1.clients.AddGroupRequest\x1a*.woodhouse.api.v1.clients.AddGroupResponse\x12j\n" +
	"\vUpdateGroup\x12,.woodhouse.api.v1.clients.UpdateGroupRequest\x1a-.woodhouse.api.v1.clients.UpdateGroupResponse\x12j\n" +
	"\vRemoveGroup\x12,.woodhouse.api.v1.clients.RemoveGroupRequest\x1a-.woodhouse.api.v1.clients.RemoveGroupResponse\x12a\n" +
	"\n" +
	"SendAction\x12'.woodhouse.api.v1.clients.ActionRequest\x1a(.woodhouse.api.v1.clients.ActionResponse0\x01\x12i\n" +
	"\x10SendImageRequest\x12*.woodhouse.api.v1.clients.UserImageRequest\x1a'.woodhouse.api.v1.clients.ImageResponse0\x01\x12o\n" +
	"\fImagesStream\x12-.woodhouse.api.v1.clients.ImagesStreamRequest\x1a..woodhouse.api.v1.clients.ImagesStreamResponse0\x01\x12l\n" +
	"\vUsersStream\x12,.woodhouse.api.v1.clients.UsersStreamRequest\x1a-.woodhouse.api.v1.clients.UsersStreamResponse0\x01\x12^\n" +
	"\aAddUser\x12(.woodhouse.api.v1.clients.AddUserRequest\x1a).woodhouse.api.v1.clients.AddUserResponse\x12g\n" +
	"\n" +
	"UpdateUser\x12+.woodhouse.api.v1.clients.UpdateUserRequest\x1a,.woodhouse.api.v1.clients.UpdateUserResponse\x12g\n" +
	"\n" +
	"RemoveUser\x12+.woodhouse.api.v1.clients.RemoveUserRequest\x1a,.woodhouse.api.v1.clients.RemoveUserResponseB=Z;github.com/jimjibone/woodhouse-api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_user_service_proto_rawDescOnce sync.Once
	file_clients_user_service_proto_rawDescData []byte
)

func file_clients_user_service_proto_rawDescGZIP() []byte {
	file_clients_user_service_proto_rawDescOnce.Do(func() {
		file_clients_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_user_service_proto_rawDesc), len(file_clients_user_service_proto_rawDesc)))
	})
	return file_clients_user_service_proto_rawDescData
}

var file_clients_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clients_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_clients_user_service_proto_goTypes = []any{
	(UserRole)(0),                         // 0: woodhouse.api.v1.clients.UserRole
	(*GetClientsRequest)(nil),             // 1: woodhouse.api.v1.clients.GetClientsRequest
	(*ClientsStreamRequest)(nil),          // 2: woodhouse.api.v1.clients.ClientsStreamRequest
	(*ClientsStreamResponse)(nil),         // 3: woodhouse.api.v1.clients.ClientsStreamResponse
	(*PairingRequestsStreamRequest)(nil),  // 4: woodhouse.api.v1.clients.PairingRequestsStreamRequest
	(*PairingRequestsStreamResponse)(nil), // 5: woodhouse.api.v1.clients.PairingRequestsStreamResponse
	(*ApprovePairingRequest)(nil),         // 6: woodhouse.api.v1.clients.ApprovePairingRequest
	(*ApprovePairingResponse)(nil),        // 7: woodhouse.api.v1.clients.ApprovePairingResponse
	(*DenyPairingRequest)(nil),            // 8: woodhouse.api.v1.clients.DenyPairingRequest
	(*DenyPairingResponse)(nil),           // 9: woodhouse.api.v1.clients.DenyPairingResponse
	(*UnpairClientRequest)(nil),           // 10: woodhouse.api.v1.clients.UnpairClientRequest
	(*UnpairClientResponse)(nil),          // 11: woodhouse.api.v1.clients.UnpairClientResponse
	(*ForgetClientRequest)(nil),           // 12: woodhouse.api.v1.clients.ForgetClientRequest
	(*ForgetClientResponse)(nil),          // 13: woodhouse.api.v1.clients.ForgetClientResponse
	(*GetDevicesRequest)(nil),             // 14: woodhouse.api.v1.clients.GetDevicesRequest
	(*DevicesStreamRequest)(nil),          // 15: woodhouse.api.v1.clients.DevicesStreamRequest
	(*DevicesStreamResponse)(nil),         // 16: woodhouse.api.v1.clients.DevicesStreamResponse
	(*RemoveDeviceRequest)(nil),           // 17: woodhouse.api.v1.clients.RemoveDeviceRequest
	(*RemoveDeviceResponse)(nil),          // 18: woodhouse.api.v1.clients.RemoveDeviceResponse
	(*DeviceService)(nil),                 // 19: woodhouse.api.v1.clients.DeviceService
	(*FavoritesStreamRequest)(nil),        // 20: woodhouse.api.v1.clients.FavoritesStreamRequest
	(*FavoritesStreamResponse)(nil),       // 21: woodhouse.api.v1.clients.FavoritesStreamResponse
	(*AddFavoriteRequest)(nil),            // 22: woodhouse.api.v1.clients.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),           // 23: woodhouse.api.v1.clients.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),         // 24: woodhouse.api.v1.clients.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil),        // 25: woodhouse.api.v1.clients.RemoveFavoriteResponse
	(*GroupsStreamRequest)(nil),           // 26: woodhouse.api.v1.clients.GroupsStreamRequest
	(*GroupsStreamResponse)(nil),          // 27: woodhouse.api.v1.clients.GroupsStreamResponse
	(*AddGroupRequest)(nil),               // 28: woodhouse.api.v1.clients.AddGroupRequest
	(*AddGroupResponse)(nil),              // 29: woodhouse.api.v1.clients.AddGroupResponse
	(*UpdateGroupRequest)(nil),            // 30: woodhouse.api.v1.clients.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),           // 31: woodhouse.api.v1.clients.UpdateGroupResponse
	(*RemoveGroupRequest)(nil),            // 32: woodhouse.api.v1.clients.RemoveGroupRequest
	(*RemoveGroupResponse)(nil),           // 33: woodhouse.api.v1.clients.RemoveGroupResponse
	(*UsersStreamRequest)(nil),            // 34: woodhouse.api.v1.clients.UsersStreamRequest
	(*UsersStreamResponse)(nil),           // 35: woodhouse.api.v1.clients.UsersStreamResponse
	(*AddUserRequest)(nil),                // 36: woodhouse.api.v1.clients.AddUserRequest
	(*AddUserResponse)(nil),               // 37: woodhouse.api.v1.clients.AddUserResponse
	(*UpdateUserRequest)(nil),             // 38: woodhouse.api.v1.clients.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 39: woodhouse.api.v1.clients.UpdateUserResponse
	(*RemoveUserRequest)(nil),             // 40: woodhouse.api.v1.clients.RemoveUserRequest
	(*RemoveUserResponse)(nil),            // 41: woodhouse.api.v1.clients.RemoveUserResponse
	(*ImagesStreamRequest)(nil),           // 42: woodhouse.api.v1.clients.ImagesStreamRequest
	(*ImageSizeHint)(nil),                 // 43: woodhouse.api.v1.clients.ImageSizeHint
	(*UserImageRequest)(nil),              // 44: woodhouse.api.v1.clients.UserImageRequest
	(*ImagesStreamResponse)(nil),          // 45: woodhouse.api.v1.clients.ImagesStreamResponse
	(*User)(nil),                          // 46: woodhouse.api.v1.clients.User
	(*Client)(nil),                        // 47: woodhouse.api.v1.clients.Client
	(*PairingRequest)(nil),                // 48: woodhouse.api.v1.clients.PairingRequest
	(*Device)(nil),                        // 49: woodhouse.api.v1.clients.Device
	(*TimeValue)(nil),                     // 50: woodhouse.api.v1.clients.TimeValue
	(*Service)(nil),                       // 51: woodhouse.api.v1.clients.Service
	(*Group)(nil),                         // 52: woodhouse.api.v1.clients.Group
	(Service_ServiceType)(0),              // 53: woodhouse.api.v1.clients.Service.ServiceType
	(*GroupMember)(nil),                   // 54: woodhouse.api.v1.clients.GroupMember
	(*ActionRequest)(nil),                 // 55: woodhouse.api.v1.clients.ActionRequest
	(*ActionResponse)(nil),                // 56: woodhouse.api.v1.clients.ActionResponse
	(*ImageResponse)(nil),                 // 57: woodhouse.api.v1.clients.ImageResponse
}
var file_clients_user_service_proto_depIdxs = []int32{
	47, // 0: woodhouse.api.v1.clients.ClientsStreamResponse.client:type_name -> woodhouse.api.v1.clients.Client
	48, // 1: woodhouse.api.v1.clients.PairingRequestsStreamResponse.pairing_request:type_name -> woodhouse.api.v1.clients.PairingRequest
	49, // 2: woodhouse.api.v1.clients.DevicesStreamResponse.device:type_name -> woodhouse.api.v1.clients.Device
	50, // 3: woodhouse.api.v1.clients.DeviceService.last_seen:type_name -> woodhouse.api.v1.clients.TimeValue
	51, // 4: woodhouse.api.v1.clients.DeviceService.service:type_name -> woodhouse.api.v1.clients.Service
	19, // 5: woodhouse.api.v1.clients.FavoritesStreamResponse.device_service:type_name -> woodhouse.api.v1.clients.DeviceService
	52, // 6: woodhouse.api.v1.clients.GroupsStreamResponse.group_update:type_name -> woodhouse.api.v1.clients.Group
	53, // 7: woodhouse.api.v1.clients.AddGroupRequest.type:type_name -> woodhouse.api.v1.clients.Service.ServiceType
	54, // 8: woodhouse.api.v1.clients.AddGroupRequest.members:type_name -> woodhouse.api.v1.clients.GroupMember
	52, // 9: woodhouse.api.v1.clients.AddGroupResponse.group:type_name -> woodhouse.api.v1.clients.Group
	54, // 10: woodhouse.api.v1.clients.UpdateGroupRequest.members:type_name -> woodhouse.api.v1.clients.GroupMember
	46, // 11: woodhouse.api.v1.clients.UsersStreamResponse.user:type_name -> woodhouse.api.v1.clients.User
	0,  // 12: woodhouse.api.v1.clients.AddUserRequest.role:type_name -> woodhouse.api.v1.clients.UserRole
	0,  // 13: woodhouse.api.v1.clients.UpdateUserRequest.role:type_name -> woodhouse.api.v1.clients.UserRole
	43, // 14: woodhouse.api.v1.clients.ImagesStreamRequest.size_hints:type_name -> woodhouse.api.v1.clients.ImageSizeHint
	0,  // 15: woodhouse.api.v1.clients.User.role:type_name -> woodhouse.api.v1.clients.UserRole
	1,  // 16: woodhouse.api.v1.clients.UserService.GetClients:input_type -> woodhouse.api.v1.clients.GetClientsRequest
	2,  // 17: woodhouse.api.v1.clients.UserService.ClientsStream:input_type -> woodhouse.api.v1.clients.ClientsStreamRequest
	4,  // 18: woodhouse.api.v1.clients.UserService.PairingRequestsStream:input_type -> woodhouse.api.v1.clients.PairingRequestsStreamRequest
	6,  // 19: woodhouse.api.v1.clients.UserService.ApprovePairing:input_type -> woodhouse.api.v1.clients.ApprovePairingRequest
	8,  // 20: woodhouse.api.v1.clients.UserService.DenyPairing:input_type -> woodhouse.api.v1.clients.DenyPairingRequest
	10, // 21: woodhouse.api.v1.clients.UserService.UnpairClient:input_type -> woodhouse.api.v1.clients.UnpairClientRequest
	12, // 22: woodhouse.api.v1.clients.UserService.ForgetClient:input_type -> woodhouse.api.v1.clients.ForgetClientRequest
	14, // 23: woodhouse.api.v1.clients.UserService.GetDevices:input_type -> woodhouse.api.v1.clients.GetDevicesRequest
	15, // 24: woodhouse.api.v1.clients.UserService.DevicesStream:input_type -> woodhouse.api.v1.clients.DevicesStreamRequest
	17, // 25: woodhouse.api.v1.clients.UserService.RemoveDevice:input_type -> woodhouse.api.v1.clients.RemoveDeviceRequest
	20, // 26: woodhouse.api.v1.clients.UserService.FavoritesStream:input_type -> woodhouse.api.v1.clients.FavoritesStreamRequest
	22, // 27: woodhouse.api.v1.clients.UserService.AddFavorite:input_type -> woodhouse.api.v1.clients.AddFavoriteRequest
	24, // 28: woodhouse.api.v1.clients.UserService.RemoveFavorite:input_type -> woodhouse.api.v1.clients.RemoveFavoriteRequest
	26, // 29: woodhouse.api.v1.clients.UserService.GroupsStream:input_type -> woodhouse.api.v1.clients.GroupsStreamRequest
	28, // 30: woodhouse.api.v1.clients.UserService.AddGroup:input_type -> woodhouse.api.v1.clients.AddGroupRequest
	30, // 31: woodhouse.api.v1.clients.UserService.UpdateGroup:input_type -> woodhouse.api.v1.clients.UpdateGroupRequest
	32, // 32: woodhouse.api.v1.clients.UserService.RemoveGroup:input_type -> woodhouse.api.v1.clients.RemoveGroupRequest
	55, // 33: woodhouse.api.v1.clients.UserService.SendAction:input_type -> woodhouse.api.v1.clients.ActionRequest
	44, // 34: woodhouse.api.v1.clients.UserService.SendImageRequest:input_type -> woodhouse.api.v1.clients.UserImageRequest
	42, // 35: woodhouse.api.v1.clients.UserService.ImagesStream:input_type -> woodhouse.api.v1.clients.ImagesStreamRequest
	34, // 36: woodhouse.api.v1.clients.UserService.UsersStream:input_type -> woodhouse.api.v1.clients.UsersStreamRequest
	36, // 37: woodhouse.api.v1.clients.UserService.AddUser:input_type -> woodhouse.api.v1.clients.AddUserRequest
	38, // 38: woodhouse.api.v1.clients.UserService.UpdateUser:input_type -> woodhouse.api.v1.clients.UpdateUserRequest
	40, // 39: woodhouse.api.v1.clients.UserService.RemoveUser:input_type -> woodhouse.api.v1.clients.RemoveUserRequest
	47, // 40: woodhouse.api.v1.clients.UserService.GetClients:output_type -> woodhouse.api.v1.clients.Client
	3,  // 41: woodhouse.api.v1.clients.UserService.ClientsStream:output_type -> woodhouse.api.v1.clients.ClientsStreamResponse
	5,  // 42: woodhouse.api.v1.clients.UserService.PairingRequestsStream:output_type -> woodhouse.api.v1.clients.PairingRequestsStreamResponse
	7,  // 43: woodhouse.api.v1.clients.UserService.ApprovePairing:output_type -> woodhouse.api.v1.clients.ApprovePairingResponse
	9,  // 44: woodhouse.api.v1.clients.UserService.DenyPairing:output_type -> woodhouse.api.v1.clients.DenyPairingResponse
	11, // 45: woodhouse.api.v1.clients.UserService.UnpairClient:output_type -> woodhouse.api.v1.clients.UnpairClientResponse
	13, // 46: woodhouse.api.v1.clients.UserService.ForgetClient:output_type -> woodhouse.api.v1.clients.ForgetClientResponse
	49, // 47: woodhouse.api.v1.clients.UserService.GetDevices:output_type -> woodhouse.api.v1.clients.Device
	16, // 48: woodhouse.api.v1.clients.UserService.DevicesStream:output_type -> woodhouse.api.v1.clients.DevicesStreamResponse
	18, // 49: woodhouse.api.v1.clients.UserService.RemoveDevice:output_type -> woodhouse.api.v1.clients.RemoveDeviceResponse
	21, // 50: woodhouse.api.v1.clients.UserService.FavoritesStream:output_type -> woodhouse.api.v1.clients.FavoritesStreamResponse
	23, // 51: woodhouse.api.v1.clients.UserService.AddFavorite:output_type -> woodhouse.api.v1.clients.AddFavoriteResponse
	25, // 52: woodhouse.api.v1.clients.UserService.RemoveFavorite:output_type -> woodhouse.api.v1.clients.RemoveFavoriteResponse
	27, // 53: woodhouse.api.v1.clients.UserService.GroupsStream:output_type -> woodhouse.api.v1.clients.GroupsStreamResponse
	29, // 54: woodhouse.api.v1.clients.UserService.AddGroup:output_type -> woodhouse.api.v1.clients.AddGroupResponse
	31, // 55: woodhouse.api.v1.clients.UserService.UpdateGroup:output_type -> woodhouse.api.v1.clients.UpdateGroupResponse
	33, // 56: woodhouse.api.v1.clients.UserService.RemoveGroup:output_type -> woodhouse.api.v1.clients.RemoveGroupResponse
	56, // 57: woodhouse.api.v1.clients.UserService.SendAction:output_type -> woodhouse.api.v1.clients.ActionResponse
	57, // 58: woodhouse.api.v1.clients.UserService.SendImageRequest:output_type -> woodhouse.api.v1.clients.ImageResponse
	45, // 59: woodhouse.api.v1.clients.UserService.ImagesStream:output_type -> woodhouse.api.v1.clients.ImagesStreamResponse
	35, // 60: woodhouse.api.v1.clients.UserService.UsersStream:output_type -> woodhouse.api.v1.clients.UsersStreamResponse
	37, // 61: woodhouse.api.v1.clients.UserService.AddUser:output_type -> woodhouse.api.v1.clients.AddUserResponse
	39, // 62: woodhouse.api.v1.clients.UserService.UpdateUser:output_type -> woodhouse.api.v1.clients.UpdateUserResponse
	41, // 63: woodhouse.api.v1.clients.UserService.RemoveUser:output_type -> woodhouse.api.v1.clients.RemoveUserResponse
	40, // [40:64] is the sub-list for method output_type
	16, // [16:40] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_clients_user_service_proto_init() }
func file_clients_user_service_proto_init() {
	if File_clients_user_service_proto != nil {
		return
	}
	file_clients_client_proto_init()
	file_clients_client_service_proto_init()
	file_clients_group_proto_init()
	file_clients_user_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_clients_user_service_proto_msgTypes[29].OneofWrappers = []any{}
	file_clients_user_service_proto_msgTypes[37].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_user_service_proto_rawDesc), len(file_clients_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_user_service_proto_goTypes,
		DependencyIndexes: file_clients_user_service_proto_depIdxs,
		EnumInfos:         file_clients_user_service_proto_enumTypes,
		MessageInfos:      file_clients_user_service_proto_msgTypes,
	}.Build()
	File_clients_user_service_proto = out.File
	file_clients_user_service_proto_goTypes = nil
	file_clients_user_service_proto_depIdxs = nil
}
