// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: clients/user_service.proto

package clientsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetClients_FullMethodName            = "/woodhouse.api.v1.clients.UserService/GetClients"
	UserService_ClientsStream_FullMethodName         = "/woodhouse.api.v1.clients.UserService/ClientsStream"
	UserService_PairingRequestsStream_FullMethodName = "/woodhouse.api.v1.clients.UserService/PairingRequestsStream"
	UserService_ApprovePairing_FullMethodName        = "/woodhouse.api.v1.clients.UserService/ApprovePairing"
	UserService_DenyPairing_FullMethodName           = "/woodhouse.api.v1.clients.UserService/DenyPairing"
	UserService_UnpairClient_FullMethodName          = "/woodhouse.api.v1.clients.UserService/UnpairClient"
	UserService_ForgetClient_FullMethodName          = "/woodhouse.api.v1.clients.UserService/ForgetClient"
	UserService_GetDevices_FullMethodName            = "/woodhouse.api.v1.clients.UserService/GetDevices"
	UserService_DevicesStream_FullMethodName         = "/woodhouse.api.v1.clients.UserService/DevicesStream"
	UserService_RemoveDevice_FullMethodName          = "/woodhouse.api.v1.clients.UserService/RemoveDevice"
	UserService_FavoritesStream_FullMethodName       = "/woodhouse.api.v1.clients.UserService/FavoritesStream"
	UserService_AddFavorite_FullMethodName           = "/woodhouse.api.v1.clients.UserService/AddFavorite"
	UserService_RemoveFavorite_FullMethodName        = "/woodhouse.api.v1.clients.UserService/RemoveFavorite"
	UserService_GroupsStream_FullMethodName          = "/woodhouse.api.v1.clients.UserService/GroupsStream"
	UserService_AddGroup_FullMethodName              = "/woodhouse.api.v1.clients.UserService/AddGroup"
	UserService_UpdateGroup_FullMethodName           = "/woodhouse.api.v1.clients.UserService/UpdateGroup"
	UserService_RemoveGroup_FullMethodName           = "/woodhouse.api.v1.clients.UserService/RemoveGroup"
	UserService_SendAction_FullMethodName            = "/woodhouse.api.v1.clients.UserService/SendAction"
	UserService_SendImageRequest_FullMethodName      = "/woodhouse.api.v1.clients.UserService/SendImageRequest"
	UserService_ImagesStream_FullMethodName          = "/woodhouse.api.v1.clients.UserService/ImagesStream"
	UserService_UsersStream_FullMethodName           = "/woodhouse.api.v1.clients.UserService/UsersStream"
	UserService_AddUser_FullMethodName               = "/woodhouse.api.v1.clients.UserService/AddUser"
	UserService_UpdateUser_FullMethodName            = "/woodhouse.api.v1.clients.UserService/UpdateUser"
	UserService_RemoveUser_FullMethodName            = "/woodhouse.api.v1.clients.UserService/RemoveUser"
	UserService_GetSettings_FullMethodName           = "/woodhouse.api.v1.clients.UserService/GetSettings"
	UserService_UpdateSettings_FullMethodName        = "/woodhouse.api.v1.clients.UserService/UpdateSettings"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// Get the current Client states. This returns a stream of Clients which
	// will close once all Clients are sent. Use ClientsStream method to get a
	// stream of current Client states and updates.
	GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Client], error)
	// Get a stream of Client updates. The first batch of replies will be the
	// current state of the clients, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty response) which
	// should be ignored, but can be used to monitor the stream for disconnects.
	ClientsStream(ctx context.Context, in *ClientsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientsStreamResponse], error)
	// Get a stream of pending pairing requests and updates. The first batch of
	// replies will be the current set, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty response) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	PairingRequestsStream(ctx context.Context, in *PairingRequestsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairingRequestsStreamResponse], error)
	// Approve a pairing request.
	ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error)
	// Deny a pairing request.
	DenyPairing(ctx context.Context, in *DenyPairingRequest, opts ...grpc.CallOption) (*DenyPairingResponse, error)
	// Unpair a client and invalidate auth tokens.
	UnpairClient(ctx context.Context, in *UnpairClientRequest, opts ...grpc.CallOption) (*UnpairClientResponse, error)
	// Forget a client (unpair then forget).
	ForgetClient(ctx context.Context, in *ForgetClientRequest, opts ...grpc.CallOption) (*ForgetClientResponse, error)
	// Get the current device states. This returns a stream of devices which
	// will close once all devices are sent. Use DevicesStream method to get a
	// stream of current device states and updates.
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error)
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DevicesStream(ctx context.Context, in *DevicesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DevicesStreamResponse], error)
	// Remove a device. This will remove the device from the system.
	RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*RemoveDeviceResponse, error)
	// Get a stream of DeviceService updates for favorites. The first batch of
	// replies will be the current state of the favorites, followed by updates
	// when they occur. The stream also includes a 10 second heartbeat (an empty
	// response) which should be ignored, but can be used to monitor the stream
	// for disconnects.
	FavoritesStream(ctx context.Context, in *FavoritesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FavoritesStreamResponse], error)
	AddFavorite(ctx context.Context, in *AddFavoriteRequest, opts ...grpc.CallOption) (*AddFavoriteResponse, error)
	RemoveFavorite(ctx context.Context, in *RemoveFavoriteRequest, opts ...grpc.CallOption) (*RemoveFavoriteResponse, error)
	// Get a stream of Group updates for groups. The first batch of replies will
	// be the current state of the group infos, followed by updates when they
	// occur. The stream also includes a 10 second heartbeat (an empty response)
	// which should be ignored, but can be used to monitor the stream for
	// disconnects.
	GroupsStream(ctx context.Context, in *GroupsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupsStreamResponse], error)
	AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	RemoveGroup(ctx context.Context, in *RemoveGroupRequest, opts ...grpc.CallOption) (*RemoveGroupResponse, error)
	// Send an action to a device service.
	SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error)
	// Send an image request to a device service. This will also update the
	// server-side image cache and push the new image to all ImagesStream
	// subscribers. The optional width and height fields act as a size hint;
	// the server will resize the image before caching and streaming.
	SendImageRequest(ctx context.Context, in *UserImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageResponse], error)
	// Get a stream of camera image updates. The first batch of replies will be
	// the current cached image for each known camera, followed by updates as
	// the server polls cameras on a schedule or a user triggers a refresh via
	// SendImageRequest. The stream also includes a 10 second heartbeat (an
	// empty response) which should be ignored.
	ImagesStream(ctx context.Context, in *ImagesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImagesStreamResponse], error)
	// Get a stream of User updates. The first batch of replies will be the
	// current state of the users, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty User) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	UsersStream(ctx context.Context, in *UsersStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UsersStreamResponse], error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error)
	// Get the current server settings.
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	// Update the server settings. Only the fields present in the request are
	// applied. Returns the settings as stored, after normalisation.
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Client], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_GetClients_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetClientsRequest, Client]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GetClientsClient = grpc.ServerStreamingClient[Client]

func (c *userServiceClient) ClientsStream(ctx context.Context, in *ClientsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], UserService_ClientsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientsStreamRequest, ClientsStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_ClientsStreamClient = grpc.ServerStreamingClient[ClientsStreamResponse]

func (c *userServiceClient) PairingRequestsStream(ctx context.Context, in *PairingRequestsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairingRequestsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[2], UserService_PairingRequestsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PairingRequestsStreamRequest, PairingRequestsStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_PairingRequestsStreamClient = grpc.ServerStreamingClient[PairingRequestsStreamResponse]

func (c *userServiceClient) ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePairingResponse)
	err := c.cc.Invoke(ctx, UserService_ApprovePairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DenyPairing(ctx context.Context, in *DenyPairingRequest, opts ...grpc.CallOption) (*DenyPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyPairingResponse)
	err := c.cc.Invoke(ctx, UserService_DenyPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnpairClient(ctx context.Context, in *UnpairClientRequest, opts ...grpc.CallOption) (*UnpairClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpairClientResponse)
	err := c.cc.Invoke(ctx, UserService_UnpairClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ForgetClient(ctx context.Context, in *ForgetClientRequest, opts ...grpc.CallOption) (*ForgetClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetClientResponse)
	err := c.cc.Invoke(ctx, UserService_ForgetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[3], UserService_GetDevices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDevicesRequest, Device]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GetDevicesClient = grpc.ServerStreamingClient[Device]

func (c *userServiceClient) DevicesStream(ctx context.Context, in *DevicesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DevicesStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[4], UserService_DevicesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DevicesStreamRequest, DevicesStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_DevicesStreamClient = grpc.ServerStreamingClient[DevicesStreamResponse]

func (c *userServiceClient) RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*RemoveDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDeviceResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FavoritesStream(ctx context.Context, in *FavoritesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FavoritesStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[5], UserService_FavoritesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FavoritesStreamRequest, FavoritesStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_FavoritesStreamClient = grpc.ServerStreamingClient[FavoritesStreamResponse]

func (c *userServiceClient) AddFavorite(ctx context.Context, in *AddFavoriteRequest, opts ...grpc.CallOption) (*AddFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFavoriteResponse)
	err := c.cc.Invoke(ctx, UserService_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveFavorite(ctx context.Context, in *RemoveFavoriteRequest, opts ...grpc.CallOption) (*RemoveFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFavoriteResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GroupsStream(ctx context.Context, in *GroupsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[6], UserService_GroupsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GroupsStreamRequest, GroupsStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GroupsStreamClient = grpc.ServerStreamingClient[GroupsStreamResponse]

func (c *userServiceClient) AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGroupResponse)
	err := c.cc.Invoke(ctx, UserService_AddGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveGroup(ctx context.Context, in *RemoveGroupRequest, opts ...grpc.CallOption) (*RemoveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveGroupResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[7], UserService_SendAction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionRequest, ActionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SendActionClient = grpc.ServerStreamingClient[ActionResponse]

func (c *userServiceClient) SendImageRequest(ctx context.Context, in *UserImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[8], UserService_SendImageRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserImageRequest, ImageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SendImageRequestClient = grpc.ServerStreamingClient[ImageResponse]

func (c *userServiceClient) ImagesStream(ctx context.Context, in *ImagesStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImagesStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[9], UserService_ImagesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImagesStreamRequest, ImagesStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_ImagesStreamClient = grpc.ServerStreamingClient[ImagesStreamResponse]

func (c *userServiceClient) UsersStream(ctx context.Context, in *UsersStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UsersStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[10], UserService_UsersStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UsersStreamRequest, UsersStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UsersStreamClient = grpc.ServerStreamingClient[UsersStreamResponse]

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, UserService_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, UserService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSettingsResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// Get the current Client states. This returns a stream of Clients which
	// will close once all Clients are sent. Use ClientsStream method to get a
	// stream of current Client states and updates.
	GetClients(*GetClientsRequest, grpc.ServerStreamingServer[Client]) error
	// Get a stream of Client updates. The first batch of replies will be the
	// current state of the clients, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty response) which
	// should be ignored, but can be used to monitor the stream for disconnects.
	ClientsStream(*ClientsStreamRequest, grpc.ServerStreamingServer[ClientsStreamResponse]) error
	// Get a stream of pending pairing requests and updates. The first batch of
	// replies will be the current set, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty response) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	PairingRequestsStream(*PairingRequestsStreamRequest, grpc.ServerStreamingServer[PairingRequestsStreamResponse]) error
	// Approve a pairing request.
	ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error)
	// Deny a pairing request.
	DenyPairing(context.Context, *DenyPairingRequest) (*DenyPairingResponse, error)
	// Unpair a client and invalidate auth tokens.
	UnpairClient(context.Context, *UnpairClientRequest) (*UnpairClientResponse, error)
	// Forget a client (unpair then forget).
	ForgetClient(context.Context, *ForgetClientRequest) (*ForgetClientResponse, error)
	// Get the current device states. This returns a stream of devices which
	// will close once all devices are sent. Use DevicesStream method to get a
	// stream of current device states and updates.
	GetDevices(*GetDevicesRequest, grpc.ServerStreamingServer[Device]) error
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DevicesStream(*DevicesStreamRequest, grpc.ServerStreamingServer[DevicesStreamResponse]) error
	// Remove a device. This will remove the device from the system.
	RemoveDevice(context.Context, *RemoveDeviceRequest) (*RemoveDeviceResponse, error)
	// Get a stream of DeviceService updates for favorites. The first batch of
	// replies will be the current state of the favorites, followed by updates
	// when they occur. The stream also includes a 10 second heartbeat (an empty
	// response) which should be ignored, but can be used to monitor the stream
	// for disconnects.
	FavoritesStream(*FavoritesStreamRequest, grpc.ServerStreamingServer[FavoritesStreamResponse]) error
	AddFavorite(context.Context, *AddFavoriteRequest) (*AddFavoriteResponse, error)
	RemoveFavorite(context.Context, *RemoveFavoriteRequest) (*RemoveFavoriteResponse, error)
	// Get a stream of Group updates for groups. The first batch of replies will
	// be the current state of the group infos, followed by updates when they
	// occur. The stream also includes a 10 second heartbeat (an empty response)
	// which should be ignored, but can be used to monitor the stream for
	// disconnects.
	GroupsStream(*GroupsStreamRequest, grpc.ServerStreamingServer[GroupsStreamResponse]) error
	AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	RemoveGroup(context.Context, *RemoveGroupRequest) (*RemoveGroupResponse, error)
	// Send an action to a device service.
	SendAction(*ActionRequest, grpc.ServerStreamingServer[ActionResponse]) error
	// Send an image request to a device service. This will also update the
	// server-side image cache and push the new image to all ImagesStream
	// subscribers. The optional width and height fields act as a size hint;
	// the server will resize the image before caching and streaming.
	SendImageRequest(*UserImageRequest, grpc.ServerStreamingServer[ImageResponse]) error
	// Get a stream of camera image updates. The first batch of replies will be
	// the current cached image for each known camera, followed by updates as
	// the server polls cameras on a schedule or a user triggers a refresh via
	// SendImageRequest. The stream also includes a 10 second heartbeat (an
	// empty response) which should be ignored.
	ImagesStream(*ImagesStreamRequest, grpc.ServerStreamingServer[ImagesStreamResponse]) error
	// Get a stream of User updates. The first batch of replies will be the
	// current state of the users, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty User) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	UsersStream(*UsersStreamRequest, grpc.ServerStreamingServer[UsersStreamResponse]) error
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	RemoveUser(context.Context, *RemoveUserRequest) (*RemoveUserResponse, error)
	// Get the current server settings.
	GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error)
	// Update the server settings. Only the fields present in the request are
	// applied. Returns the settings as stored, after normalisation.
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetClients(*GetClientsRequest, grpc.ServerStreamingServer[Client]) error {
	return status.Error(codes.Unimplemented, "method GetClients not implemented")
}
func (UnimplementedUserServiceServer) ClientsStream(*ClientsStreamRequest, grpc.ServerStreamingServer[ClientsStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientsStream not implemented")
}
func (UnimplementedUserServiceServer) PairingRequestsStream(*PairingRequestsStreamRequest, grpc.ServerStreamingServer[PairingRequestsStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method PairingRequestsStream not implemented")
}
func (UnimplementedUserServiceServer) ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePairing not implemented")
}
func (UnimplementedUserServiceServer) DenyPairing(context.Context, *DenyPairingRequest) (*DenyPairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DenyPairing not implemented")
}
func (UnimplementedUserServiceServer) UnpairClient(context.Context, *UnpairClientRequest) (*UnpairClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpairClient not implemented")
}
func (UnimplementedUserServiceServer) ForgetClient(context.Context, *ForgetClientRequest) (*ForgetClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetClient not implemented")
}
func (UnimplementedUserServiceServer) GetDevices(*GetDevicesRequest, grpc.ServerStreamingServer[Device]) error {
	return status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedUserServiceServer) DevicesStream(*DevicesStreamRequest, grpc.ServerStreamingServer[DevicesStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method DevicesStream not implemented")
}
func (UnimplementedUserServiceServer) RemoveDevice(context.Context, *RemoveDeviceRequest) (*RemoveDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDevice not implemented")
}
func (UnimplementedUserServiceServer) FavoritesStream(*FavoritesStreamRequest, grpc.ServerStreamingServer[FavoritesStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method FavoritesStream not implemented")
}
func (UnimplementedUserServiceServer) AddFavorite(context.Context, *AddFavoriteRequest) (*AddFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedUserServiceServer) RemoveFavorite(context.Context, *RemoveFavoriteRequest) (*RemoveFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedUserServiceServer) GroupsStream(*GroupsStreamRequest, grpc.ServerStreamingServer[GroupsStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GroupsStream not implemented")
}
func (UnimplementedUserServiceServer) AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGroup not implemented")
}
func (UnimplementedUserServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedUserServiceServer) RemoveGroup(context.Context, *RemoveGroupRequest) (*RemoveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroup not implemented")
}
func (UnimplementedUserServiceServer) SendAction(*ActionRequest, grpc.ServerStreamingServer[ActionResponse]) error {
	return status.Error(codes.Unimplemented, "method SendAction not implemented")
}
func (UnimplementedUserServiceServer) SendImageRequest(*UserImageRequest, grpc.ServerStreamingServer[ImageResponse]) error {
	return status.Error(codes.Unimplemented, "method SendImageRequest not implemented")
}
func (UnimplementedUserServiceServer) ImagesStream(*ImagesStreamRequest, grpc.ServerStreamingServer[ImagesStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ImagesStream not implemented")
}
func (UnimplementedUserServiceServer) UsersStream(*UsersStreamRequest, grpc.ServerStreamingServer[UsersStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method UsersStream not implemented")
}
func (UnimplementedUserServiceServer) AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) RemoveUser(context.Context, *RemoveUserRequest) (*RemoveUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedUserServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedUserServiceServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetClients_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetClientsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetClients(m, &grpc.GenericServerStream[GetClientsRequest, Client]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GetClientsServer = grpc.ServerStreamingServer[Client]

func _UserService_ClientsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ClientsStream(m, &grpc.GenericServerStream[ClientsStreamRequest, ClientsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_ClientsStreamServer = grpc.ServerStreamingServer[ClientsStreamResponse]

func _UserService_PairingRequestsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PairingRequestsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).PairingRequestsStream(m, &grpc.GenericServerStream[PairingRequestsStreamRequest, PairingRequestsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_PairingRequestsStreamServer = grpc.ServerStreamingServer[PairingRequestsStreamResponse]

func _UserService_ApprovePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ApprovePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ApprovePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ApprovePairing(ctx, req.(*ApprovePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DenyPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DenyPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DenyPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DenyPairing(ctx, req.(*DenyPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnpairClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpairClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnpairClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnpairClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnpairClient(ctx, req.(*UnpairClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ForgetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ForgetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ForgetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ForgetClient(ctx, req.(*ForgetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetDevices(m, &grpc.GenericServerStream[GetDevicesRequest, Device]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GetDevicesServer = grpc.ServerStreamingServer[Device]

func _UserService_DevicesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DevicesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).DevicesStream(m, &grpc.GenericServerStream[DevicesStreamRequest, DevicesStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_DevicesStreamServer = grpc.ServerStreamingServer[DevicesStreamResponse]

func _UserService_RemoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveDevice(ctx, req.(*RemoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FavoritesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FavoritesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).FavoritesStream(m, &grpc.GenericServerStream[FavoritesStreamRequest, FavoritesStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_FavoritesStreamServer = grpc.ServerStreamingServer[FavoritesStreamResponse]

func _UserService_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddFavorite(ctx, req.(*AddFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveFavorite(ctx, req.(*RemoveFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GroupsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GroupsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GroupsStream(m, &grpc.GenericServerStream[GroupsStreamRequest, GroupsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_GroupsStreamServer = grpc.ServerStreamingServer[GroupsStreamResponse]

func _UserService_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddGroup(ctx, req.(*AddGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveGroup(ctx, req.(*RemoveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).SendAction(m, &grpc.GenericServerStream[ActionRequest, ActionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SendActionServer = grpc.ServerStreamingServer[ActionResponse]

func _UserService_SendImageRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).SendImageRequest(m, &grpc.GenericServerStream[UserImageRequest, ImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SendImageRequestServer = grpc.ServerStreamingServer[ImageResponse]

func _UserService_ImagesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImagesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ImagesStream(m, &grpc.GenericServerStream[ImagesStreamRequest, ImagesStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_ImagesStreamServer = grpc.ServerStreamingServer[ImagesStreamResponse]

func _UserService_UsersStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UsersStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).UsersStream(m, &grpc.GenericServerStream[UsersStreamRequest, UsersStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UsersStreamServer = grpc.ServerStreamingServer[UsersStreamResponse]

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.v1.clients.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApprovePairing",
			Handler:    _UserService_ApprovePairing_Handler,
		},
		{
			MethodName: "DenyPairing",
			Handler:    _UserService_DenyPairing_Handler,
		},
		{
			MethodName: "UnpairClient",
			Handler:    _UserService_UnpairClient_Handler,
		},
		{
			MethodName: "ForgetClient",
			Handler:    _UserService_ForgetClient_Handler,
		},
		{
			MethodName: "RemoveDevice",
			Handler:    _UserService_RemoveDevice_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _UserService_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _UserService_RemoveFavorite_Handler,
		},
		{
			MethodName: "AddGroup",
			Handler:    _UserService_AddGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _UserService_UpdateGroup_Handler,
		},
		{
			MethodName: "RemoveGroup",
			Handler:    _UserService_RemoveGroup_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _UserService_RemoveUser_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _UserService_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _UserService_UpdateSettings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClients",
			Handler:       _UserService_GetClients_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientsStream",
			Handler:       _UserService_ClientsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PairingRequestsStream",
			Handler:       _UserService_PairingRequestsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDevices",
			Handler:       _UserService_GetDevices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DevicesStream",
			Handler:       _UserService_DevicesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FavoritesStream",
			Handler:       _UserService_FavoritesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GroupsStream",
			Handler:       _UserService_GroupsStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendAction",
			Handler:       _UserService_SendAction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendImageRequest",
			Handler:       _UserService_SendImageRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImagesStream",
			Handler:       _UserService_ImagesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UsersStream",
			Handler:       _UserService_UsersStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clients/user_service.proto",
}
