// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: clients/user_auth_service.proto

package clientsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_clients_user_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_clients_user_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UserRefreshRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken   string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RenewThreshold uint32                 `protobuf:"varint,2,opt,name=renew_threshold,json=renewThreshold,proto3" json:"renew_threshold,omitempty"` // Days remaining before expiry to cause the refresh token to be renewed. Set to zero to always renew.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserRefreshRequest) Reset() {
	*x = UserRefreshRequest{}
	mi := &file_clients_user_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshRequest) ProtoMessage() {}

func (x *UserRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshRequest.ProtoReflect.Descriptor instead.
func (*UserRefreshRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserRefreshRequest) GetRenewThreshold() uint32 {
	if x != nil {
		return x.RenewThreshold
	}
	return 0
}

type UserRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRefreshResponse) Reset() {
	*x = UserRefreshResponse{}
	mi := &file_clients_user_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshResponse) ProtoMessage() {}

func (x *UserRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshResponse.ProtoReflect.Descriptor instead.
func (*UserRefreshResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserRefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserRefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UserLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogoutRequest) Reset() {
	*x = UserLogoutRequest{}
	mi := &file_clients_user_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutRequest) ProtoMessage() {}

func (x *UserLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutRequest.ProtoReflect.Descriptor instead.
func (*UserLogoutRequest) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserLogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogoutResponse) Reset() {
	*x = UserLogoutResponse{}
	mi := &file_clients_user_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutResponse) ProtoMessage() {}

func (x *UserLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_user_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutResponse.ProtoReflect.Descriptor instead.
func (*UserLogoutResponse) Descriptor() ([]byte, []int) {
	return file_clients_user_auth_service_proto_rawDescGZIP(), []int{5}
}

var File_clients_user_auth_service_proto protoreflect.FileDescriptor

const file_clients_user_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1fclients/user_auth_service.proto\x12\x18woodhouse.api.v1.clients\"J\n" +
	"\x10UserLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x11UserLoginResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"b\n" +
	"\x12UserRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12'\n" +
	"\x0frenew_threshold\x18\x02 \x01(\rR\x0erenewThreshold\"]\n" +
	"\x13UserRefreshResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"8\n" +
	"\x11UserLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x14\n" +
	"\x12UserLogoutResponse2\xc6\x02\n" +
	"\x0fUserAuthService\x12b\n" +
	"\x05Login\x12*.woodhouse.api.v1.clients.UserLoginRequest\x1a+.woodhouse.api.v1.clients.UserLoginResponse\"\x00\x12h\n" +
	"\aRefresh\x12,.woodhouse.api.v1.clients.UserRefreshRequest\x1a-.woodhouse.api.v1.clients.UserRefreshResponse\"\x00\x12e\n" +
	"\x06Logout\x12+.woodhouse.api.v1.clients.UserLogoutRequest\x1a,.woodhouse.api.v1.clients.UserLogoutResponse\"\x00B=Z;github.com/jimjibone/woodhouse-api/go/v1/clients;clientsapib\x06proto3"

var (
	file_clients_user_auth_service_proto_rawDescOnce sync.Once
	file_clients_user_auth_service_proto_rawDescData []byte
)

func file_clients_user_auth_service_proto_rawDescGZIP() []byte {
	file_clients_user_auth_service_proto_rawDescOnce.Do(func() {
		file_clients_user_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_user_auth_service_proto_rawDesc), len(file_clients_user_auth_service_proto_rawDesc)))
	})
	return file_clients_user_auth_service_proto_rawDescData
}

var file_clients_user_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clients_user_auth_service_proto_goTypes = []any{
	(*UserLoginRequest)(nil),    // 0: woodhouse.api.v1.clients.UserLoginRequest
	(*UserLoginResponse)(nil),   // 1: woodhouse.api.v1.clients.UserLoginResponse
	(*UserRefreshRequest)(nil),  // 2: woodhouse.api.v1.clients.UserRefreshRequest
	(*UserRefreshResponse)(nil), // 3: woodhouse.api.v1.clients.UserRefreshResponse
	(*UserLogoutRequest)(nil),   // 4: woodhouse.api.v1.clients.UserLogoutRequest
	(*UserLogoutResponse)(nil),  // 5: woodhouse.api.v1.clients.UserLogoutResponse
}
var file_clients_user_auth_service_proto_depIdxs = []int32{
	0, // 0: woodhouse.api.v1.clients.UserAuthService.Login:input_type -> woodhouse.api.v1.clients.UserLoginRequest
	2, // 1: woodhouse.api.v1.clients.UserAuthService.Refresh:input_type -> woodhouse.api.v1.clients.UserRefreshRequest
	4, // 2: woodhouse.api.v1.clients.UserAuthService.Logout:input_type -> woodhouse.api.v1.clients.UserLogoutRequest
	1, // 3: woodhouse.api.v1.clients.UserAuthService.Login:output_type -> woodhouse.api.v1.clients.UserLoginResponse
	3, // 4: woodhouse.api.v1.clients.UserAuthService.Refresh:output_type -> woodhouse.api.v1.clients.UserRefreshResponse
	5, // 5: woodhouse.api.v1.clients.UserAuthService.Logout:output_type -> woodhouse.api.v1.clients.UserLogoutResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clients_user_auth_service_proto_init() }
func file_clients_user_auth_service_proto_init() {
	if File_clients_user_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_user_auth_service_proto_rawDesc), len(file_clients_user_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_user_auth_service_proto_goTypes,
		DependencyIndexes: file_clients_user_auth_service_proto_depIdxs,
		MessageInfos:      file_clients_user_auth_service_proto_msgTypes,
	}.Build()
	File_clients_user_auth_service_proto = out.File
	file_clients_user_auth_service_proto_goTypes = nil
	file_clients_user_auth_service_proto_depIdxs = nil
}
